# Generated by Django 3.2.11 on 2022-01-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_grade_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionattachment",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
