# Generated by Django 3.2.11 on 2022-01-13 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_alter_submissionattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionattachment",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="submissions.submission",
            ),
        ),
    ]
