# Generated by Django 3.2.11 on 2022-01-13 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_alter_submissionattachment_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionattachment",
            name="submitted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
