# Generated by Django 3.2.11 on 2023-05-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_auto_20230517_1130'),
        ('submissions', '0007_auto_20220501_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='assignments.assignment'),
        ),
    ]
