# Generated by Django 3.2.11 on 2023-06-03 17:29

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set each submission's planned_activity to the PlannedActivity associated with the PiecePlan associated with its assignment."""
        
    Submission = apps.get_model("submissions", "Submission")
    PlannedActivity = apps.get_model("assignments", "PlannedActivity")
    Assignment = apps.get_model("assignments", "Assignment")

    submissions = Submission.objects.all()

    for submission in submissions:
        assignment = submission.assignment
        piece_plan = assignment.piece_plan
        planned_activity = PlannedActivity.objects.get(piece_plan=piece_plan)
        submission.planned_activity = planned_activity
        submission.save()


def update_site_backward(apps, schema_editor):
    """Set each submission's planned_activity to None."""
        
    Submission = apps.get_model("submissions", "Submission")

    submissions = Submission.objects.all()

    for submission in submissions:
        submission.planned_activity = None
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_submission_planned_activity'),
        ('assignments', '0024_create_pieceplans_for_assignments'),
    ]

    operations = [
        migrations.RunPython(update_site_forward, update_site_backward)
    ]
