# Generated by Django 3.2.11 on 2022-01-07 21:56

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Transposition = apps.get_model("instruments", "Transposition")
    Transposition.objects.update_or_create(
        name="Alto Clef",
    )
    Transposition.objects.update_or_create(
        name="Bb",
    )
    Transposition.objects.update_or_create(
        name="Concert Pitch BC",
    )
    Transposition.objects.update_or_create(
        name="Concert Pitch BC 8vb",
    )
    Transposition.objects.update_or_create(
        name="Concert Pitch TC",
    )
    Transposition.objects.update_or_create(
        name="Concert Pitch TC 8va",
    )
    Transposition.objects.update_or_create(
        name="Eb",
    )
    Transposition.objects.update_or_create(
        name="F",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0001_initial"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
