# Generated by Django 3.2.11 on 2022-01-07 23:36

from django.db import migrations

def initial_instruments(apps, schema_editor):
    Transposition = apps.get_model("instruments", "Transposition")
    transpositions = {elem.name:elem for elem in Transposition.objects.all()}
    Instrument = apps.get_model("instruments", "Instrument")
    Instrument.objects.update_or_create(
        name="Viola",
        transposition=transpositions["Alto Clef"],
    )
    Instrument.objects.update_or_create(
        name="Baritone TC",
        transposition=transpositions["Bb"],
    )
    Instrument.objects.update_or_create(
        name="Bass Clarinet",
        transposition=transpositions["Bb"],
    )
    Instrument.objects.update_or_create(
        name="Bb Clarinet",
        transposition=transpositions["Bb"],
    )
    Instrument.objects.update_or_create(
        name="Bb Cornet",
        transposition=transpositions["Bb"],
    )
    Instrument.objects.update_or_create(
        name="Bb Soprano Saxophone",
        transposition=transpositions["Bb"],
    )
    Instrument.objects.update_or_create(
        name="Bb Tenor Saxophone",
        transposition=transpositions["Bb"],
    )
    Instrument.objects.update_or_create(
        name="Bb Trumpet",
        transposition=transpositions["Bb"],
    )
    Instrument.objects.update_or_create(
        name="Bassoon",
        transposition=transpositions["Concert Pitch BC"],
    )
    Instrument.objects.update_or_create(
        name="Cello",
        transposition=transpositions["Concert Pitch BC"],
    )
    Instrument.objects.update_or_create(
        name="Euphonium BC",
        transposition=transpositions["Concert Pitch BC"],
    )
    Instrument.objects.update_or_create(
        name="Trombone",
        transposition=transpositions["Concert Pitch BC"],
    )
    Instrument.objects.update_or_create(
        name="Bass",
        transposition=transpositions["Concert Pitch BC 8vb"],
    )
    Instrument.objects.update_or_create(
        name="Bass Trombone",
        transposition=transpositions["Concert Pitch BC 8vb"],
    )
    Instrument.objects.update_or_create(
        name="Contrabassoon",
        transposition=transpositions["Concert Pitch BC 8vb"],
    )
    Instrument.objects.update_or_create(
        name="String Bass",
        transposition=transpositions["Concert Pitch BC 8vb"],
    )
    Instrument.objects.update_or_create(
        name="Tuba",
        transposition=transpositions["Concert Pitch BC 8vb"],
    )
    Instrument.objects.update_or_create(
        name="Oboe",
        transposition=transpositions["Concert Pitch TC"],
    )
    Instrument.objects.update_or_create(
        name="Percussion",
        transposition=transpositions["Concert Pitch TC"],
    )
    Instrument.objects.update_or_create(
        name="Piano",
        transposition=transpositions["Concert Pitch TC"],
    )
    Instrument.objects.update_or_create(
        name="Flute",
        transposition=transpositions["Concert Pitch TC 8va"],
    )
    Instrument.objects.update_or_create(
        name="Piccolo",
        transposition=transpositions["Concert Pitch TC 8va"],
    )
    Instrument.objects.update_or_create(
        name="Violin",
        transposition=transpositions["Concert Pitch TC 8va"],
    )
    Instrument.objects.update_or_create(
        name="Contrabass Clarinet",
        transposition=transpositions["Eb"],
    )
    Instrument.objects.update_or_create(
        name="Eb Alto Clarinet",
        transposition=transpositions["Eb"],
    )
    Instrument.objects.update_or_create(
        name="Eb Alto Horn",
        transposition=transpositions["Eb"],
    )
    Instrument.objects.update_or_create(
        name="Eb Alto Saxophone",
        transposition=transpositions["Eb"],
    )
    Instrument.objects.update_or_create(
        name="Eb Baritone Saxophone",
        transposition=transpositions["Eb"],
    )
    Instrument.objects.update_or_create(
        name="Eb Soprano Clarinet",
        transposition=transpositions["Eb"],
    )
    Instrument.objects.update_or_create(
        name="F Horn",
        transposition=transpositions["F"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_data_migration_seed_transpositions'),
    ]

    operations = [migrations.RunPython(initial_instruments, migrations.RunPython.noop)]
