# Generated by Django 3.2.11 on 2024-03-18 19:39

from django.db import migrations, models

def initial_instrument_program_numbers(apps, schema_editor):
    INSTRUMENT_PNS = {
        "Viola":  42,
        "Baritone TC": 58,
        "Bass Clarinet": 72,
        "Bb Clarinet": 72,
        "Bb Cornet": 57,
        "Bb Soprano Saxophone": 65,
        "Bb Tenor Saxophone": 67,
        "Bb Trumpet": 57,
        "Bassoon": 71,
        "Cello":  43,
        "Euphonium BC": 58,
        "Trombone": 58,
        "Bass":  33,
        "Bass Trombone": 58,
        "Contrabassoon": 71,
        "String Bass": 33,
        "Tuba":  59,
        "Oboe":  69,
        "Percussion": 13,
        "Piano":  1,
        "Flute":  74,
        "Piccolo": 73,
        "Violin": 41,
        "Contrabass Clarinet": 72,
        "Eb Alto Clarinet": 72,
        "Eb Alto Horn": 61,
        "Eb Alto Saxophone": 66,
        "Eb Baritone Saxophone": 68,
        "Eb Soprano Clarinet": 72,
        "F Horn": 61,
    }

    for instrument_name, program_number in INSTRUMENT_PNS.items():
        Instrument = apps.get_model("instruments", "Instrument")
        instrument = Instrument.objects.get(name=instrument_name)
        instrument.midi_program_number = program_number
        instrument.save()

class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_data_migration_seed_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='midi_program_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(initial_instrument_program_numbers, migrations.RunPython.noop)
    ]
