# Generated by Django 3.2.11 on 2022-01-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="EnsembleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Ensemble Type",
                "verbose_name_plural": "Ensemble Types",
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("video", models.URLField(blank=True)),
                ("audio", models.URLField(blank=True)),
                ("date_composed", models.DateField(blank=True, null=True)),
                (
                    "composer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="musics.composer",
                    ),
                ),
                (
                    "ensemble_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="musics.ensembletype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartTransposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notation", models.URLField()),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="musics.part"
                    ),
                ),
                (
                    "transposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="instruments.transposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part Transposition",
                "verbose_name_plural": "Part Transpositions",
            },
        ),
        migrations.AddField(
            model_name="part",
            name="piece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="musics.piece"
            ),
        ),
    ]
