# Generated by Django 3.2.11 on 2022-01-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0002_seed_ensemble_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composer",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
