# Generated by Django 3.2.11 on 2022-01-14 02:22

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    PartType = apps.get_model("musics", "PartType")
    for name in ["Melody", "Bassline", "Combined"]:
        PartType.objects.update_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0004_auto_20220113_2122"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
