# Generated by Django 3.2.11 on 2022-01-14 02:24

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Part = apps.get_model("musics", "Part")
    PartType = apps.get_model("musics", "PartType")
    pt = PartType.objects.all().first()

    for p in Part.objects.all():
        p.part_type = pt
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0005_seed_part_types"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
