# Generated by Django 3.2.11 on 2022-01-14 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0006_legitimize_part_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="part_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="musics.parttype"
            ),
        ),
    ]
