# Generated by Django 3.2.11 on 2022-01-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0007_alter_part_part_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parttransposition",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transpositions",
                to="musics.part",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="composer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="musics.composer",
            ),
        ),
    ]
