# Generated by Django 3.2.11 on 2022-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0008_auto_20220113_2248"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parttransposition",
            name="notation",
        ),
        migrations.AddField(
            model_name="parttransposition",
            name="flatio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
