# Generated by Django 3.2.11 on 2022-01-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0009_auto_20220113_2315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="piece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parts",
                to="musics.piece",
            ),
        ),
    ]
