# Generated by Django 3.2.11 on 2022-01-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0010_alter_part_piece"),
        ("instruments", "0003_data_migration_seed_instruments"),
    ]

    operations = [migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)]
