# Generated by Django 3.2.11 on 2022-01-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0013_assign_piece_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.SlugField(),
        ),
    ]
