# Generated by Django 3.2.11 on 2022-03-28 03:41

from django.db import migrations

import json
from teleband.musics.api.serializers import *

data = {
    "name": "Air for Band",
    "ensemble_type": "Band",
    "parts": [
        {
            "name": "Air for Band Melody",
            "part_type": "Melody",
            "transpositions": [
                {"transposition": "Bb"},
                {"transposition": "Concert Pitch BC 8vb"},
                {"transposition": "Concert Pitch BC"},
                {"transposition": "Concert Pitch TC 8va"},
                {"transposition": "Concert Pitch TC"},
                {"transposition": "Eb"},
                {"transposition": "F"},
            ],
        },
        {
            "name": "Air for Band Bassline",
            "part_type": "Bassline",
            "transpositions": [
                {"transposition": "Bb"},
                {"transposition": "Concert Pitch BC 8vb"},
                {"transposition": "Concert Pitch BC"},
                {"transposition": "Concert Pitch TC 8va"},
                {"transposition": "Concert Pitch TC"},
                {"transposition": "Eb"},
                {"transposition": "F"},
            ],
        },
    ],
}

flatios = {
    "Air for Band Melody": {
        "Bb": {
            "scoreId": "61e09029dffcd50014571a80",
            "sharingKey": "169f2baebaa5721b4442b124fc984cce26f7e63312fb597d187f9c4d0e3aa1897df093c3bec76af250eb3ca0f36eb4f645ac70f470a695ccd217a1ce0cd52120",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "61e09029f7c4ec0013a88255",
            "sharingKey": "da2261d04292fb3ec8562a5fd1ac167e70937ee5c531bf51ba01a49e7629e4df47c838c488e5b2e978d72a2885879787c1f2357b46b35abecc6f8308c943c35f",
        },
        "Concert Pitch BC": {
            "scoreId": "61e0902a29718e0012080b97",
            "sharingKey": "7399632fbfbc793448182049dead3b88d921d7fab4328b5b9f5c589e654374d1d12a86d2e5567df1723b33e517b392552371129a9302bda49930f3e8a28dd857",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "61e0902a58d51b001256f80c",
            "sharingKey": "11f725a4c13735b5e1a98903393699f066fd267f965d3d5ebea65f9bbd103ae5924cd3a26abfbc801f59aa0f71e66ee325192e397546cb648c4f4fc58cbb3490",
        },
        "Concert Pitch TC": {
            "scoreId": "61e0902a32669f0013f6f91d",
            "sharingKey": "25540b6b552a61fb0e95ed89986563b4a1b2caf566c114e2f48d1a8531866fca93e51681bf52ed4e0bedae3900b8781bccb84f51027b70bdc3f964d8a6a6e9aa",
        },
        "Eb": {
            "scoreId": "61e0902a74bfb70013c4ea3e",
            "sharingKey": "a88d609cd8c2224ccef9c043b03622ee11cd02390343eb9bbf3830b17929602ce138f7e623c99d9ebbbb291d9a415d62519ba5321b870be84c5fef49008f6d6e",
        },
        "F": {
            "scoreId": "61e0902a1ffc3c00126dc83a",
            "sharingKey": "7a9c959174769c7998d654218ba1d5c39054cf889f888e5b8eae871f2f4ccdca0d603a42266f45c875274263eb214cd517698bde86960dbdb088d4975bf33764",
        },
    },
    "Air for Band Bassline": {
        "Bb": {
            "scoreId": "61e0902832669f0013f6f8cf",
            "sharingKey": "176abdfc4283560ad234533e5a392e0ced4ea08f9f799a165dd950d66debf48daa293211ee11a56e98f1e62a6b6b12dd2d5d50085a866ea3910f9b721bf0cb11",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "61e0902874bfb70013c4e9f0",
            "sharingKey": "3a573e7fe487d00b76bbe5bff5cf1350ce1b6a94938be7cd8f9ec70c647aaeb1af65c3b35fc31543d5c6f0648095a79edd73d3c7e05d33b79b2f2a6e3734d609",
        },
        "Concert Pitch BC": {
            "scoreId": "61e090281ffc3c00126dc7d6",
            "sharingKey": "b6a819a7636cfc5e7842417ce68d598725ca98b184b7997321ae15dd3b2a14f82622d249175d9fd308f00636cf3c7f28ad0a5dde6a309ca7ab7c37f01170404b",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "61e09028c9707c0013966a6d",
            "sharingKey": "1bf46c7b7cf16bf5d06b9dbb9d822c54299ed092bc3f3a0d3209d0f776b23fe1dbb49a49d7d7b97f9fad460c2c0ea42cd1c572eced32e734c28f26f8f064d989",
        },
        "Concert Pitch TC": {
            "scoreId": "61e090281cad9a0012110fa6",
            "sharingKey": "6e674328b917912c10d6e00cdfb5128da374b4fb77dbaa638f9be457fc512d96589068b88fa6830e907a5d28b8f60c252ea78df8b8e75bab6af1344a2210b582",
        },
        "Eb": {
            "scoreId": "61e090290f63e200125c8da7",
            "sharingKey": "6609d33e30426aeaf95279321291501cc8296da784b6c96fc2bdd6fdad968ed94faa3508e1b3bb609a537d9be3246a63b8d6c38273814a228728f6765de7208f",
        },
        "F": {
            "scoreId": "61e090290bd92f0012185daa",
            "sharingKey": "224061dc8f008b68e3f1ffb1d9de357a88f655557fd26b735f6f67761521195c51368775ab30b9e82d1f03f08d23611ff84796d198e4ba5b09dc1d458202de26",
        },
    },
}


def update_site_forward(apps, schema_editor):
    Piece = apps.get_model("musics", "Piece")
    if Piece.objects.filter(name="Air for Band").exists():
        return

    for part in data["parts"]:
        for t in part["transpositions"]:
            t["flatio"] = json.dumps(flatios[part["name"]][t["transposition"]])

    serializer = PieceCreateSerializer(data=data)
    serializer.is_valid()
    serializer.create(serializer.validated_data)


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0015_auto_20220206_2027'),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
