# Generated by Django 3.2.11 on 2022-08-16 19:00

from django.db import migrations

import json
from teleband.musics.api.serializers import *

data = [
    {
        "name": "Celebration for a New Day",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Celebration_for_a_New_Day_Accompaniment.mp3",
        "parts": [
            {
                "name": "Celebration for a New Day Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Celebration for a New Day Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "America the Beautiful",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/America_the_Beautiful_Accompaniment.mp3",
        "parts": [
            {
                "name": "America the Beautiful Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "America the Beautiful Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "The Favorite",
        "ensemble_type": "Orchestra",
        "accompaniment": "",
        "video": "https://www.youtube.com/embed/ErLjmovOrcQ",
        "parts": [
            {
                "name": "The Favorite Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Alto Clef"},
                ],
            },
            {
                "name": "The Favorite Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Alto Clef"},
                ],
            },
        ],
    },
    {
        "name": "Freedom 2040 (Band)",
        "ensemble_type": "Band",
        "video": "https://www.youtube.com/embed/rrdimNIWhAw",
        "accompaniment": "accompaniments/Freedom_2040_-_Accompaniment.mp3",
        "parts": [
            {
                "name": "Freedom 2040 (Band) Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Freedom 2040 (Band) Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Freedom 2040 (Orchestra)",
        "ensemble_type": "Orchestra",
        "video": "https://www.youtube.com/embed/rrdimNIWhAw",
        "accompaniment": "accompaniments/Freedom_2040_-_Accompaniment.mp3",
        "parts": [
            {
                "name": "Freedom 2040 (Orchestra) Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Alto Clef"},
                ],
            },
            {
                "name": "Freedom 2040 (Orchestra) Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Alto Clef"},
                ],
            },
        ],
    },
    {
        "name": "Down by the Riverside",
        "ensemble_type": "Band",
        "video": "https://www.youtube.com/embed/8Z32Spi1amQ",
        "accompaniment": "accompaniments/Down_by_the_Riverside_-_Accompaniment.mp3",
        "parts": [
            {
                "name": "Down by the Riverside Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Down by the Riverside Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Deep River",
        "ensemble_type": "Band",
        "video": "https://www.youtube.com/embed/8Z32Spi1amQ",
        "accompaniment": "accompaniments/Deep_River_-_Accompaniment.mp3",
        "parts": [
            {
                "name": "Deep River Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Deep River Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "I Want to be Ready",
        "ensemble_type": "Band",
        "video": "https://www.youtube.com/embed/8Z32Spi1amQ",
        "accompaniment": "accompaniments/I_Want_to_be_Ready_-_Accompaniment.mp3",
        "parts": [
            {
                "name": "I Want to be Ready Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "I Want to be Ready Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
]

flatios = {
    "Celebration for a New Day Melody": {
        "Bb": {
            "scoreId": "628e69a5265cae0012f92102",
            "sharingKey": "6cc05969d633913707859b61f50e34476d3ca1634d9c307eab870fc77e0aa85bba6ce4841b7589b591fca6a56c1af7722d8679c28820183398567df5a6866ffb",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "628e5d65fcae000013e25d83",
            "sharingKey": "2ddcef3e459d09e958c07324098f1a0eb8a57535279756a9da41b4a998a96d32d8f7709e28f97a27b598fd0b364565712dcc0940c448cedbb61e2d356aef6e5b",
        },
        "Concert Pitch BC": {
            "scoreId": "628e5c8c67a4c00013675d44",
            "sharingKey": "f232c662b79998c7008dc534d1c9aa72c1b6e48253ea9bf1d246d1143a8eb59993de22763af66d88dc38f6b622747de634b1378df0aa444f1358c676508c8d91",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "628e5d232b51630012a3178a",
            "sharingKey": "8f500c083bf551b967cc8a757c2bd50aa2de56487f8b68337134cb7e014313d1b81e96b8d6ccaf87b9ba8acee19d30734d878211ea80b892982f18a5dd2710fd",
        },
        "Concert Pitch TC": {
            "scoreId": "628e5797265cae0012f82b63",
            "sharingKey": "84ea53d182c21f1339e75329a63bd580e62aecd2534d24edc70bb141b9617c62895bf2779a4acda39716cb0293b8d91a3f9747053f2bfdfb327dc929f80d4d6c",
        },
        "Eb": {
            "scoreId": "628e69e9a9fb870014536e50",
            "sharingKey": "254f88dbe7929604344578e7872a67a7278beb8441f16747c215aea2059cf9d35576c5cfd7b693f4ef40610418dbb603534963c46da67d93685ed725907f1893",
        },
        "F": {
            "scoreId": "628e6a320b1bbe00159b21c3",
            "sharingKey": "106d5f553c5ded9bd2ed7da45298beb39c5c1f655e603c7421001b9f3ea4290db2c1dc50eeaa58153142cce8ad5770401ac1f837577a7a8de77c23cbbc7a1657",
        },
    },
    "Celebration for a New Day Bassline": {
        "Bb": {
            "scoreId": "628e4bdbe022a00012d592c3",
            "sharingKey": "22b29e314b3bd60e79af4bd56332c5a4a8cd3e0a6b84905f4478c4a695810c64299c5e8e01e4ac42c94e04cd90a7e0dc5cbe810e8d3b077a02a753ed6b9ecd78",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "628e4b51b9541a00120d2fc7",
            "sharingKey": "5254c6a346ca1b1fc1ee4f1301bba060868a1d5df06cd71709db46aaf024755ff60a3ac42d167751ff108537b2ffe486c433d4e588f136ab0f259f7e15c96c51",
        },
        "Concert Pitch BC": {
            "scoreId": "628e482bac9d160012747fcd",
            "sharingKey": "9610ce8aef4d0a6f570f1fd934e70138a0166b4f60f6bedbfbcd2bdf3ba4c90d0b21003eb24fdda6880a7cf0be9b4f7c1ea477a908e205061e078422a4325e6f",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "628e4af4ad55ab00124e5e6e",
            "sharingKey": "4eea559c3bcf7b269a0e842fb9da9b47e7c0ac31146e3a15916f56edebf7c06d285f8dd7e5a3ca1471b86234bc74bf50f05a77fc25d8a6cf551d93c5cf7c2f24",
        },
        "Concert Pitch TC": {
            "scoreId": "628e4592240e1a0012c10893",
            "sharingKey": "f10376228f2676dbec97c644e30a998a08af7b45ed7fdeb3044274a9f8f9baf2c233e7e8b887b954d74b576df3db48eae1ebbece036ab20ec29311fcf689a5e8",
        },
        "Eb": {
            "scoreId": "628e4cb21561640012936397",
            "sharingKey": "34dbeafd7deacc52ceafbe86890a00e8c554c5b78418e6d2e4d30bfaed1a11471cd03db5d670da79d3fdf83590f861af48fb70ae5437504d3b550878cad27945",
        },
        "F": {
            "scoreId": "628e4d4e31b18000127d1850",
            "sharingKey": "065f00c8a326f46aa18f7fb6b4aaab44c3fd5bc2fa7c4d98d94620e885a2f983c1cf9e8b0eaf0dd61deddea65eec300ce091a8c1b86bdb20812f8f899809cb52",
        },
    },
    "America the Beautiful Melody": {
        "Bb": {
            "scoreId": "62632e7d4e0f760012b02caf",
            "sharingKey": "9e817d6676a3d22c84b2d6a8270187ffcaa8a4900f235cd112b0ca4e877e0b3a476e39ed6c7a154287f174b94022330c60702c9b09ca0dedfbd0f0f7b18a5a9d",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62632da8e54da20013399b94",
            "sharingKey": "4c5e4b873acfb21190780a195644a33fbbc4fce1afb7ee502ec50120a9218facaa5dfd2446bf042028acd6ca76b8c95b4989fa6716f89f14764ee1cbadf0468a",
        },
        "Concert Pitch BC": {
            "scoreId": "62632d42794e2700136d27a2",
            "sharingKey": "eba992ba02dc336b16eb0dd50a15363f66ab79939d569af145a1d61cedac2bd9ba9a518e57c4e7143df5b22c916ceeebbbad9563ecdd2560eaea018498302015",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62632c856947e7001263c703",
            "sharingKey": "b12a6c27f68b81a2ff6eef28929eed0f5448c6a73431e85068672dc111ce051221774a7bfa37121538df3d900787a8a23f0809b2eeb3093d79e62f6fb3d8176d",
        },
        "Concert Pitch TC": {
            "scoreId": "6261dd35e9271f001371657a",
            "sharingKey": "f6910f85ad1177f31883cb7fcdcc5396aa74969d8573e9fa6bc8c7c04ed7f930cada05c6be588902aa4502609455d2b7a76e220d7028f5048ba1828f2194a0aa",
        },
        "Eb": {
            "scoreId": "62632f310171cc0012997ca5",
            "sharingKey": "a14f233536c3d007799ba6dcbf958c21bd714382f9b7c56831f356cbc782c75adaa63218f6aa795e5c01535511c33b8ac5b4c60f21e23f05cd44a0d3a720ef1a",
        },
        "F": {
            "scoreId": "62632f88e54da2001339be13",
            "sharingKey": "d01a97d98cc9cf6f1302ddbc84332f70d9c9a8938e5691bd2ae1bc63e5331a640318783505aecd1092da8aa75819fd65f1ac70373f17d00d5df4a791fc21eeb5",
        },
    },
    "America the Beautiful Bassline": {
        "Bb": {
            "scoreId": "6261dafc8e8d800013cb30a1",
            "sharingKey": "73530a316b09b39ebd6fd13f4681a6a595806a20038d18b6e9ba363c2394520084796ad53b484af259b2ca4247f4255e5e43173bec3bb3431f806503ea1e0539",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "6261d9b815b97f00135d0faf",
            "sharingKey": "cc5d7c3ebf30d49c3caa3ebe53e083aca8d956b8be8054e043b5f669760ee1144e9528c5289704c8829da6165c6d0a247525e6efbc5ce8c73c5fef2f93038492",
        },
        "Concert Pitch BC": {
            "scoreId": "6261d873481bdd001391b125",
            "sharingKey": "3f2e161ab77ffb84dff953c70c257b8de02f3e8d98d1e2d1606e1b49e9d1d6ab1d46bf95dd8710369faac37a23ebb941f45b098a2b2735c45164d5f2eced2cad",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "6261d70f14cc9c00135bb264",
            "sharingKey": "d5eaf5bf8bb0fca9228c63c7ff493cc4a978383131ae37bc14921469c6c188c52eb4c836fb08eae7026d69e195cb347c04c491aeaa00e25efe18234d7211118d",
        },
        "Concert Pitch TC": {
            "scoreId": "6261d2ac7306b50012ffef95",
            "sharingKey": "4cd8df1a1e1003f384cedecc5594f5f49eca01d609ca4c6018416b0625db7499920d6b2ef58b49a129dc03021f16b6cfaf768cead70dcc552edf6c572065e0ac",
        },
        "Eb": {
            "scoreId": "6261dbacbc871a00134accb7",
            "sharingKey": "81c8a8961846bb1718997a9b059b13314d123878d5c1d98d3e38e57a30c7dc29919247403b5a1d98c37a39fdd9b03ef1d6e0574e4319a2ac1d9d3137339fb0d1",
        },
        "F": {
            "scoreId": "6261dc21bc871a00134ad5f5",
            "sharingKey": "2417b38e97b708d2d81646db99fd1b6ea3b5a9e2507436ca98b0a389ede149ed8a9c7c2817e2d44fb19fa8884ecc5885130fd467eec58e875e52a764af74cec6",
        },
    },
    "The Favorite Melody": {
        "Concert Pitch BC 8vb": {
            "scoreId": "62a1fb9b6c75a20013a0395b",
            "sharingKey": "eee32615f0e0e107a912a0d56836307e5c01ce1ef6a09ba6bebd8e7b8449d1dd7155ea3e266a13954c5880f152a9e5d1f2f01f986581bbfad6c8f7fceb981dbc",
        },
        "Concert Pitch BC": {
            "scoreId": "62a1fb9bae279600124e12d7",
            "sharingKey": "aefb44d5719712fc741ebadd01fe54bb14539faa8678bc15b1b93b91c256466986d5cabfdff3df8f09bb252fd8de69944e4e3183dc4a493e1a7e049df2e16719",
        },
        "Concert Pitch TC": {
            "scoreId": "62a1fb9bda053500145cde38",
            "sharingKey": "ff36371f52c06ba5952fd8d79a126a542b5f8193bd145c959476c0493796fda659d2e4f54e859ac967bc076befd0e049d6446884bece317b79cb81dd1736ab9d",
        },
        "Alto Clef": {
            "scoreId": "62a1fb9aaa8f8c00120522d1",
            "sharingKey": "aa4d3e672c5e353199fa4a60baca34a195bd1f9162190c36ad223a394908f99119e9a39eafba5fb282df1a7f224cf0f50cbb571483d7c65963f36e49ac3f6a32",
        },
    },
    "The Favorite Bassline": {
        "Concert Pitch BC 8vb": {
            "scoreId": "62a1fb997f799a001260b0d6",
            "sharingKey": "3e23a320828c7233a6fd62db48fe313029a5f260ce4defc657ac62f90ab399398ec577828a4d7d4e592fdd322aa0cfc4195f1eb576844f708549e918adf71637",
        },
        "Concert Pitch BC": {
            "scoreId": "62a1fb997f799a001260b0d6",
            "sharingKey": "3e23a320828c7233a6fd62db48fe313029a5f260ce4defc657ac62f90ab399398ec577828a4d7d4e592fdd322aa0cfc4195f1eb576844f708549e918adf71637",
        },
        "Concert Pitch TC": {
            "scoreId": "62a1fb9a71a1c80013da8718",
            "sharingKey": "f2da9863df5eca277bbd84be0dfb045ffa165122a89a6db7595de0afa795b852d017bcc08c9e4d9bced1d05381c7aa0f0b7febc5657c2f7c420760680fa2172e",
        },
        "Alto Clef": {
            "scoreId": "62a1fb99b168b900125b032d",
            "sharingKey": "0c0098faf7bfcde6e7750a67e68e8267d70fbfb2deb8546b063644669f10c9023324eced439c34d7d19304c640ecf88ce4011d781009f114e01a14abf7350439",
        },
    },
    "Freedom 2040 (Band) Melody": {
        "Bb": {
            "scoreId": "62ec0df285c66a0012359804",
            "sharingKey": "8ca1af1cfd5d1470c3f4afd089db3f7078559d9726c88fa8ad8a763306eeb01ed2b9ce6a21b17744ee664259973bc5383acbdf4ab574a0a7e5b7b7974333d01c",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62ec0df32e1d0f00137ba309",
            "sharingKey": "be9b9657918bfa66953ba3f05135dffa61be83866a3705f056b761b5a540dc73e7ea6b259aac118655f7544d87bf9b6c8393eb98b3c729987fa76122a03c8a23",
        },
        "Concert Pitch BC": {
            "scoreId": "62ec0df25205540013decb45",
            "sharingKey": "66cf421ace7733fa9d91bd2b10899642c27058fe4cdbdda5d7297db2176bc4ed7b086d12c0de3a47c7e8beafc0b92a4a60a41c72c652205598a3471507ea5a12",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62ec0df2331b460012508864",
            "sharingKey": "00d4af82e89d6a4993fa87c5c1748ad9364f38b59225bc3cbbfed486957afc0237f4365162a972f361666c9c607dc571bb3c8993adb01d8c9308ad4497f3157b",
        },
        "Concert Pitch TC": {
            "scoreId": "62ec0df2c6f0b1001227613f",
            "sharingKey": "30bc11ca0306e5d4955a135fd0bd723010fb082fe006f4dd505c36ade58ded13f494a810a480215bfe02b41e60f6972b5e69f40b5f2772291e75ada7fd8cd0b3",
        },
        "Eb": {
            "scoreId": "62ec0df369980f0012f25d03",
            "sharingKey": "ab26f18f29b66c1536236cbdfbd809b776dd03143d3b71a218e970d81969584bd32c9ba6c9c415a78aeadda7089969bdf7183ad13709ed5f5bbd47c1904d20b8",
        },
        "F": {
            "scoreId": "62ec0df3c7bca900123b7779",
            "sharingKey": "c727e3336847dd1906abbba2db12569f717e4b9052810336cc4e2ef92a992259bfa073c9ebdb535fb12f76ab5022e58169a11fba4d086a95dcb271570e9ffaab",
        },
    },
    "Freedom 2040 (Band) Bassline": {
        "Bb": {
            "scoreId": "62ec1046331b46001250a8d2",
            "sharingKey": "1f26f96b6e1e150cb6db8ae51d42cd41eaedab7e18d1fd5cd3939c46ac809aedd2c8d968a2ab7f881c101bd69220c89d0a155ee66b75e7584b06fc242b50c557",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62ec1047c7bca900123b95cc",
            "sharingKey": "a9363ea7ce661dd11df7fae9b3d6c1e3397f61f5be188d1b030e64110179c66e4f3e2054bd6d5f7a30396cd5812d876382dbe417b9ecd5c7c6cf299128ba9488",
        },
        "Concert Pitch BC": {
            "scoreId": "62ec1046d043ef0013674421",
            "sharingKey": "cad1afc8b4262d5a5a5908398737892fa00d1df460bf35fef52b5d14ae0b98bbb7fa25917c52321dbccd0ea592ec53493f7eb74b94c99180831d4afd8c67cdca",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62ec10462e1d0f00137bc11e",
            "sharingKey": "77ab2d276a379d459348c130b0db69c8f0ed97c8d5a3ac9e46cca87e5ec31652c0bc7b1275e9f1995611d5ff3ef4f54e4f416e8f312e78b257d95486d20a39f7",
        },
        "Concert Pitch TC": {
            "scoreId": "62ec10462c6a9d00122d5652",
            "sharingKey": "1d60a4c5a8ad2f5a2860fad50ce73b2c73b4e9867b2ed44cf1176fb5164d69d4e7755f4c5c83d41cac47b3bbe28112f95c6c8b4d515376ebee8637a3a862f7d3",
        },
        "Eb": {
            "scoreId": "62ec1047d761f20012ce13fa",
            "sharingKey": "5de34d0111be5882361c2b41696010441f9f417696b25898bd0d5e550727e3116361c469558dd86bbab89ca9ec95849df630265f5d01dead6faeb1e3e7b8006f",
        },
        "F": {
            "scoreId": "62ec104791d8e600128cd221",
            "sharingKey": "3550f72c3cc6cbe3e3db98f7be2c432397a7ed9ed1a9a0673b76c5fdabfcf9b683c3f7b939b1d2aa41acb614b7ad778e53dd80c495888ebd97680e66876a9c28",
        },
    },
    "Freedom 2040 (Orchestra) Melody": {
        "Concert Pitch BC 8vb": {
            "scoreId": "62ee518c4104fd001292285f",
            "sharingKey": "93e9f9a504e0ddf3a75b7e1d91422a81d364d0a4de51809c5e5d0eda0f30b5f5047a06e8fa54d33711acacea698b8c0afef6ca825f119018ac2f342990ddd5d7",
        },
        "Concert Pitch BC": {
            "scoreId": "62ee518f4104fd001292288f",
            "sharingKey": "c319779db244eca10c3db169a9244934bb0930023075be5fafc86573d5c70a67702f41e21abea8d884dcf18658e4d904968b639a8de012a76cf0fecd2321879d",
        },
        "Concert Pitch TC": {
            "scoreId": "62ee518eb51bc90013a8361a",
            "sharingKey": "7f140fdc132746f968df51dc979cc06427bd0304d079eb8bbceae1244096cb509e93920640cf88fad5fcbbe2c10d03b79094c77a59f125de03f0cfdf607cc3a6",
        },
        "Alto Clef": {
            "scoreId": "62ee518e286dc10012bbbcf3",
            "sharingKey": "e5ce855375f28b7bc7cc0a928dbead9ce11a1a5b3f9883df40cd5564b7d86ca2eb08ce2ca0be8ae9c80203d54f811046447e38d28d1d4167aa75fdd3b84caab7",
        },
    },
    "Freedom 2040 (Orchestra) Bassline": {
        "Concert Pitch BC 8vb": {
            "scoreId": "62ee518e03b2f80012015097",
            "sharingKey": "f18736876b3c1c08993da72636e96f82c879488f2da85cb844dd871acb61ddeaa116584f81e752feaee96c6cae2c6b811945f3a7261a07ea12416d505602e699",
        },
        "Concert Pitch BC": {
            "scoreId": "62ee518c74d3f30012fefb8a",
            "sharingKey": "a6c19233c6a8f5bd7311bae49fe584cb8b87c4c50281548928419662428ffda3ae4ea78fc0b6a151ec31eb688e9c089467dc7ee0b0fd285ad4b1349c69494847",
        },
        "Concert Pitch TC": {
            "scoreId": "62ee518e03b2f80012015082",
            "sharingKey": "fc48da9ae5a5c399da6a16854a612ea647ac2e983ceac296b5476da3ca3e03ca47317ec161199e53f343a06d3ba5680cd75471a11b709c6d4de32e5d8295346f",
        },
        "Alto Clef": {
            "scoreId": "62ee518d03b2f80012015069",
            "sharingKey": "7465a05a5db73fdec5c226af4111e115cc3b73005b7eeab441f5fb93523bd33220677442e88b6c6d130835c41886f648ef8c8b2ad2a403098ac25ecc603a78da",
        },
    },
    "Down by the Riverside Melody": {
        "Bb": {
            "scoreId": "62ec10e6d761f20012ce1b2f",
            "sharingKey": "0e02133ac03e0c10401a5cc48096b8c31e94246a0e1e7847f2336a1a950bf488dd0013d05af7f2c9cf40aca41bf36be17d872a01746c90de4249f39ca36f7b12",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62ec10e765c08d0013b0121a",
            "sharingKey": "9ac07d12f55acda69b549f4c322464b070a8339d1c4077d68c64e8823d73c90e28e1c1d09b4fef1ef2a2d661672c8995c5b216c1fd47c02800fc8130bfe9568d",
        },
        "Concert Pitch BC": {
            "scoreId": "62ec10e62e1d0f00137bc899",
            "sharingKey": "28b8d6e6a85ba480c870c49f2e4d36499cffc5ec0a7a204f29ccecb8654271927c3a312c4db007a98a9a1b5f8dd97d82b45c22cd467456c7c973b8832621eafa",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62ec10e61198e100134164be",
            "sharingKey": "aaf7fc0592d41849454d301a96ccc33c80bdecfc6cefa671758baf6010500c65bf79f10d959b6b2b84b54df7807ad16f3b645ed6b273590755252d3d119f71a4",
        },
        "Concert Pitch TC": {
            "scoreId": "62ec10e691d8e600128cd955",
            "sharingKey": "aba8bcb1c46c842bbab275790b1d7297ec514ee670a5794067e6cf8db4014053ac784334edcaf473d7df2599996e60ba351741de977e1c33d1004531f243d205",
        },
        "Eb": {
            "scoreId": "62ec10e75205540013def1f5",
            "sharingKey": "a1f3314246124eee01098a336c17d7a081380e62c30e147e1c6b3606e767448dd01e478a25a03fc450bc05ca62cb1f9696cae7486e8deacc5dc31bcf042b3a28",
        },
        "F": {
            "scoreId": "62ec10e785c66a001235bd0e",
            "sharingKey": "cf9ad39f6c8bad212a55fcdeb3ce036c0e770d8c4434e068db80e7e3e7b00dde718a9e267522b9b34bf44b1e9f3f59838845b277258555923e87372b31d42dac",
        },
    },
    "Down by the Riverside Bassline": {
        "Bb": {
            "scoreId": "62ec12091198e10013417356",
            "sharingKey": "0173accc37efe71e3cebe5956b7bd99fadffff0294a2641b27637c5321d66f7e773488b533b34412900f4779ea8e18e0cfc0d83059878d293c3372f7c5948504",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62ec120a65c08d0013b0205d",
            "sharingKey": "479a316a8078dc30f67ad359866220498c8b788026e1a1b1cae0681d74275bc31d3f6d2565a85fdd2aa514440fbac029d9453c0407ca2ce164abe6629deb6bb4",
        },
        "Concert Pitch BC": {
            "scoreId": "62ec1208c6f0b1001227953d",
            "sharingKey": "e8e76dc16610c10cd5bc13a138725c52071ac753a56f6d96d472d540f9b21a2b095454bcc87c259990e39181f96e789b6e1e53c5b096c9c947fd3cd2792e0ffc",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62ec1208d761f20012ce2936",
            "sharingKey": "bd5c8711816e53f01865a9e00faa0df1f42de644e873f710f29595615fca739bf4a686a6b5410ecd27bd9ab480e80a393c140fa46cb75169de8eaba7ba1c23a5",
        },
        "Concert Pitch TC": {
            "scoreId": "62ec120969980f0012f29149",
            "sharingKey": "3a34a63e5f091ce96bc3c5b81dd26a4d55cfce6e5e1fa4f3eea6559bcc5ec192a81c71b75ea932e4083caa73af3f1087d94f13baf91daa356724420a152dbfe1",
        },
        "Eb": {
            "scoreId": "62ec120991d8e600128ce7d9",
            "sharingKey": "c58925bbafa3324c34cd1c9c3b3ff8fd12f0e7f4c46b9bc3b6b1371b1619cba229893103815561879fc56f798321925f4c3a1d425df8ebd7323329ade2f5abfa",
        },
        "F": {
            "scoreId": "62ec120a77e86e00128f5b9f",
            "sharingKey": "6954a10b646133b130919d7ee3a733d944bdfe3ac4aa6959ad1c52d67039c9dcfc477334c0e76a12b9db4797c78529588127977898449f29cf6fa3f26b6aa704",
        },
    },
    "Deep River Melody": {
        "Bb": {
            "scoreId": "62ec124a91d8e600128ceb0b",
            "sharingKey": "21f10c88735a17851972c78df5490eea1548045045cf805612b700a2ab2e61ad5468e260b0ccf552f1588a0b4f111193724eb5b60df42c432b75acfe47c02e24",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62ec124ba41acf00120c5555",
            "sharingKey": "81985fc4c9a578134a74183f69d13a841dd7bad87b096ef50d58e2c1811060297c022fc8e25413b5c643a1aef62c95561d939cee979f2c0d05a76cb82c7c69fa",
        },
        "Concert Pitch BC": {
            "scoreId": "62ec124a5205540013df031f",
            "sharingKey": "c2a6b6631628813194936bd398533ec27837ad9933d1ea3be606e9c3e6e8d81331bb4a0457c862cfadf2fb1446ef42ecd43bf2826d446f9748af178b4b25a186",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62ec124a331b46001250c1d6",
            "sharingKey": "6cf4eb1e62d58d12e42350d0de4d0e7489c9281361442219a95541e415ea595a88667e24536787a49aa96595292016f4065f12e3a598c2e51860eccbe5ae79f2",
        },
        "Concert Pitch TC": {
            "scoreId": "62ec124a2e1d0f00137bdab5",
            "sharingKey": "63c6af6e48945b8bc06b8698d2571e494aeeaf2531ca2d9f82a96680a233483a5b1ac1b4962b58b63f38fa6a6fc76c21e6c549f1cc29eeae0695709e2303d4a6",
        },
        "Eb": {
            "scoreId": "62ec124b77e86e00128f5ee1",
            "sharingKey": "bb8fed0fd6d20b67fd8e2cc93f6d809122eac97377d7cdacf251579974347cbc990bc4516be5245b53cec82300cf261cf46af892be9b31ac0510176ab51cedac",
        },
        "F": {
            "scoreId": "62ec124b65c08d0013b02383",
            "sharingKey": "e0bc60f4eb51919328781fb8aac246fb4c098a651d91fc33384c5b5046a614a3a6d2d1b9b34c3db8de9595986257ae67392ccf0e3cb42056caa4168ce76a0caf",
        },
    },
    "Deep River Bassline": {
        "Bb": {
            "scoreId": "62ec128791d8e600128ceec4",
            "sharingKey": "45be1d2612cd4d62ac764f72169809f1fd49cdb0196fb72e5f10636c644904c4c7138d389fd5104447b86fef22ab89905ea96d7df11b046d913f3477092d9fae",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62ec1289c7bca900123bb1fc",
            "sharingKey": "755e712d14028ba7af030060cfe27a3b26943ef7fe6b16eb158d0025c4befb5ae9f60a40afde15128e7215a0d5bbcb73edffefb0afd3da0cde9ee96f12471613",
        },
        "Concert Pitch BC": {
            "scoreId": "62ec12866674840012670a40",
            "sharingKey": "b6b0c352411aeb6f175a9b99d1d4f8fe8297a785fdd919f88f0db21f4273625d7a277def70c80c2f4b17d6058cf2aee78b1c176117829906954dcb951ad8a695",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62ec12852c6a9d00122d7435",
            "sharingKey": "0d8cb736117eb1ba7da5aad5da87dde6ee7e68c74fd3bb200ad4859a1c761cf59b45ab25ef489ff59c4b4d766a5a0fa2300cce2a4b6829af483883babed19ae1",
        },
        "Concert Pitch TC": {
            "scoreId": "62ec12872e1d0f00137bde0e",
            "sharingKey": "04bb0d0cd3cfe340051d9a3f9f3615b37d770d5ea52a2168a49a22382f6c542f185c4bc34517c00df229ae62c03faa9b6f1e9e2739feec8fa3be5fbd3a935a37",
        },
        "Eb": {
            "scoreId": "62ec128777e86e00128f624b",
            "sharingKey": "46daf805b2c7a51832f89eaf0838a443a0ae5cb0ea521d14f112cc18750e46da8c868cb02bf98d197c2386107bbf7dd7a0df63eb955666eaf5850fd27a017a4c",
        },
        "F": {
            "scoreId": "62ec1288a41acf00120c58ed",
            "sharingKey": "642dfebfa767ad16fa5a6099a49c68d244954bb55ac28e1e96aa2b8646adb36ce8d5d41fad74e9b24d75542fe1dc9d5be0269e93039d541f834ece38ff2af3ce",
        },
    },
    "I Want to be Ready Melody": {
        "Bb": {
            "scoreId": "62ec12fb2e1d0f00137be40a",
            "sharingKey": "320cff7133419e025fa15fd08461c6272cc7f888b740e08af0a2171679188f31425f320a277807e5758a8aaf4f587fc8b32fd257407f110d872f0d39f3493527",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62ec12fcc7bca900123bb7e0",
            "sharingKey": "c4de1d399d5b658905fc47d4673a7ba696b54b53fe4fa316d7d814abb41f1ff56b4993238b0be8583a012eb7ee6a2d7a8c819f050914f85a6070018e165c4c04",
        },
        "Concert Pitch BC": {
            "scoreId": "62ec12fa5205540013df0cc2",
            "sharingKey": "f8b40f3c4a88686303e78e1ba8db83ed35443f6b786c1e20a9d641b0b631170f47bb37e19dcd4db0c2ed92650ae28b9c9aba3448a1f2ca3047b0937910976723",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62ec12fa331b46001250cb13",
            "sharingKey": "d2002570944285c42257d396189722bc4ac81524e4527a22a8f0c77014f8626fb91618f4950237ac3b2d78f6f5cf8255770bedf024aa90ebf3bcdf7fab939043",
        },
        "Concert Pitch TC": {
            "scoreId": "62ec12fb77e86e00128f67e4",
            "sharingKey": "577bc3598722773d873ca627f4706fdea39c8f3d82e9183210182360baa61b1d1ab33c0d454a710f39336373b764a4d5b0fa55024d307a307a80f580f195cea3",
        },
        "Eb": {
            "scoreId": "62ec12fb7fe67400134f1b00",
            "sharingKey": "7baccb0caf4a49b21ee6c572c68d1116974c0d09317949c3368f4be8b60b0643b1b42d138bbda3808e7162f5c2f7b8117d2e7c2175bba8541a481abab0d5bf07",
        },
        "F": {
            "scoreId": "62ec12fc82487a00126116c5",
            "sharingKey": "056bb73aa6e2efcd6331a21e13a85f3bbdd06ecaa38108413d4bf13b9d0cd6792f9b4572f33c48fd5f4a2b3a536e8f8b4b9e47ba737aeb82235ed518f4f85d6a",
        },
    },
    "I Want to be Ready Bassline": {
        "Bb": {
            "scoreId": "62ec134977e86e00128f6bed",
            "sharingKey": "19ec2c7858e139e1d5c5b9889df92f5ea5a4c77e9fd2a11878347fb9cbf13885dec7aeabe872c89e79f6928d81d5e0dc3490c9b73cb62f2a562c350ddc324578",
        },
        "Concert Pitch BC 8vb": {
            "scoreId": "62ec134aa457dd001214350b",
            "sharingKey": "5c1c9a1669466b919c3f1b0deb1bffc51b1118ad11a7e5c3b52d7d42bdd4aaa612e6032ea2ad5c29e9353e5e37214ec880ee9d58a8ec61f02c72c729458eb727",
        },
        "Concert Pitch BC": {
            "scoreId": "62ec13482e1d0f00137be7c8",
            "sharingKey": "671936b550dda6401dc23f313258a694099944d5528a0bfbff8393ebb50a2bd4b17ebe566f1a971290f8a9624ba41a69db2bff5352997a35ff92be924647f485",
        },
        "Concert Pitch TC 8va": {
            "scoreId": "62ec134891d8e600128cf856",
            "sharingKey": "87739969cdc30390cd7fc466edea4f7b8c13a4bb99b94bbdbf39a74024ae1c362ac17d0b15c01868cc92beac3208464e0b6abe4d1330dabb977252aa0ef060a6",
        },
        "Concert Pitch TC": {
            "scoreId": "62ec134965c08d0013b03038",
            "sharingKey": "b952b34efa0b09bfac4278b91bc59ef19d38bc5458bd8b6b560f6589a644167e15346627c0143528bcadc0617a7e1246f38c823ec6b6a424d9729913096828e2",
        },
        "Eb": {
            "scoreId": "62ec134951fca50014f8961e",
            "sharingKey": "2db09e67740f97a79cb5d3d5a65220d6d193bde77278421ab50c4e0836544d9fe6d171fe5d55ba276d865cd1dbafd95b4369f91ea284943b18d3ba4818229e22",
        },
        "F": {
            "scoreId": "62ec134982487a0012611af4",
            "sharingKey": "7b0b91cb5d9ece7f7f1367d0630ba559826c6ff5c975de18b20f235fa7c15d6c52e60378948da2b2bb850b7b3381c8563b2b3b0e19d84110c689b81483d1c7ba",
        },
    },
}

def update_site_forward(apps, schema_editor):
    Piece = apps.get_model("musics", "Piece")
    if Piece.objects.filter(name=data[0]["name"]).exists():
        return

    for piece in data:
        for part in piece["parts"]:
            for t in part["transpositions"]:
                t["flatio"] = json.dumps(flatios[part["name"]][t["transposition"]])
        serializer = PieceCreateSerializer(data=piece)
        serializer.is_valid()
        serializer.create(serializer.validated_data)

class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0017_seed_combined_part_20220720_1413'),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]

