# Generated by Django 3.2.11 on 2023-09-12 01:50

from django.db import migrations
import json
from teleband.utils.migration_helpers import create_part_et_al, create_piece_et_al


data = [
    {
        "name": "Beginning Band - When the Saints Go Marching In",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/When the Saints Go Marching In - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - When the Saints Go Marching In Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - When the Saints Go Marching In Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - Ode to Joy",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Ode to Joy - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - Ode to Joy Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - Ode to Joy Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - London Bridge",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/London Bridge - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - London Bridge Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - London Bridge Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - Jolly Old St. Nick",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Jolly Old St. Nick - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - Jolly Old St. Nick Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - Jolly Old St. Nick Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - Jingle Bells",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Jingle Bells - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - Jingle Bells Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - Jingle Bells Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - Hot Cross Buns",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Hot Cross Buns - Accomp. (half=84).mp3",
        "parts": [
            {
                "name": "Beginning Band - Hot Cross Buns Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - Hot Cross Buns Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - Good King Wenceslas",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Good King Wenceslas  - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - Good King Wenceslas Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - Good King Wenceslas Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - Go Tell Aunt Rhody",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Go Tell Aunt Rhody - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - Go Tell Aunt Rhody Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - Go Tell Aunt Rhody Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - Aura Lee",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Aura Lee  - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - Aura Lee Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - Aura Lee Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Band - Amazing Grace",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Amazing Grace - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Band - Amazing Grace Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Band - Amazing Grace Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    {"transposition": "Eb"},
                    {"transposition": "F"},
                ],
            },
        ],
    },
]


flatios = {}
from_xml = [
    {
        "Beginning Band - When the Saints Go Marching In Melody": {
            "Alto Clef": {
                "scoreId": "64ecbd10bdb526b23298063b",
                "sharingKey": "8b8a1628b68c30b7523777b39585e5e32438b50a6f841e8abd10292c7b3e182e5813c868771e609226fd37794682d999f6bfa4f313355fac5c27c78bfba4a9ab",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Melody": {
            "Bb": {
                "scoreId": "63fad68d347443218fd25402",
                "sharingKey": "657e0024779f115d1ed87e2a09273383ddc53c8b97b78f371d863ead09942899ded25e18761ed7f246ae9f14ca55b25c62ab69182e8b9fdb739dd97b75da9a6f",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Melody": {
            "Concert Pitch BC": {
                "scoreId": "63fad509080bd14d406250d1",
                "sharingKey": "a63b997e8bf1cb46602cd6eba5c03c9b47bb3195cce308d243525bbbeef3c3f159c801dc3d2c13f6e47118407722afd59f8b6eac68adac4881b659ece808f2a3",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fad505ac7007fc340758ea",
                "sharingKey": "dccde9af0df0c20c03fcbfd7da0da102604ec4e43b9e1177aded3f16be219c644fe466502d37bee0124726482e0ed63964b2ff142ddeca42a3f840ea3b59eae0",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Melody": {
            "Concert Pitch TC": {
                "scoreId": "63fad50797f911f5b58ff25d",
                "sharingKey": "e3a5b39bd4361b764ceef2801b8b3a4d8c651a2f956ee4f3d9434449c16840136591c74a71ca4b7890c3c2e9017b275f809d8157d0119280214c748d4c247e17",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fad5059c2943098a4eb12b",
                "sharingKey": "a99ecc837d1c9ee1837c3472eed5d03d328ab2cb680a97e27fa8497c1361b42330e39192f19829bca448c097cda11fcc75a7c98e4365034e281db3b79510f38a",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Melody": {
            "Eb": {
                "scoreId": "63fad506026c5534367199c8",
                "sharingKey": "2a2e097a94069516ff9d4fbcc04b5c96a522b3cbdd97735c4cb26924733da017da759d2b81faab343ca70c810d60ce963ed98265afe16c6138f6fd0e9cedf775",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Melody": {
            "F": {
                "scoreId": "63fad5063eb3fd2d88e3cd32",
                "sharingKey": "682fec825cdee81a1325303a91e03c7e5ffbc61951b187a38e20a8a4fcb2a759e33c05fd01375fceeba227cb2852d950dad983f2c945b04a54bda041336e88cd",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Bassline": {
            "Alto Clef": {
                "scoreId": "64ecbcaeb647e205e6e8f6a4",
                "sharingKey": "a9e57de09ce0ee06eeede3fe7367436a2602817946e764a1564a07295bcdfa26e6aa5782000a33c5569cf89ee755b82773d669b2809f096ebf73762c65fe5fb6",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Bassline": {
            "Bb": {
                "scoreId": "63fb980d537dd1ccc12cf44f",
                "sharingKey": "03a605a5b23a59c5565206a0d8b94586877b81154909e146704582adf27fbc71da949937f195a6c54a3faabfb64125de595a9f450c2f9eb9abbd13c2d4b3d06f",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63fb99189e101698a2817e82",
                "sharingKey": "69305e17f46a5091cf71883a7f5a798f229367753731db113e2f61e07851c67835d4a18afebdfdd0ed26747632ed9018567e44535d1d7a709b0301d79ed3aeb2",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fb996fcb614e7a85fd25a1",
                "sharingKey": "da0355ab31e7b082964a469437a0d555daea8039b4504f97073416b675222ebcf49b49a0795fd45945dab75cd0a76f254e81171cda259f33a34fd224d843bb55",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63fb97af4b2dd03a889beb7a",
                "sharingKey": "7e26a15228ea87d12f4e984b66f0862de404a00c59d464805a27202b37a469f80f0954c2d38f5fc095630f75100174bd512a49a2c7acce1e339d81d3e27147be",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fb91c430206df5c538f4ce",
                "sharingKey": "2e19b76bbacede7196979bbf17cd5b753b9a953dc66b205a13a2523f10260025e0d2babeab1832eae3373e5b21ff5a4a3d67d23c293b6e57438315031aa9a505",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Bassline": {
            "Eb": {
                "scoreId": "63fb9879839651e6641ca549",
                "sharingKey": "3af93926e996f197146f297c2590a238f0cb05a5862a38b506f921ce1cb6b242d28ee74182d72119459b3057b59150f0a6fe05f7402376641395c7d10687b5b9",
            }
        }
    },
    {
        "Beginning Band - When the Saints Go Marching In Bassline": {
            "F": {
                "scoreId": "63fb98d4e03a983c95460b5a",
                "sharingKey": "ea05644c7b77e33659c547c08bd347997070642775e52befbc19ea4d8d0f05fe0d6b3da0eb9765955921bf733099dd4423bdc7a7531d848a88e837a5f64a8d70",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Melody": {
            "Alto Clef": {
                "scoreId": "64ee4f8c9038017bf8da1b20",
                "sharingKey": "220a28d8f56e62cf3e35228ac02679d02f49e8b24f5d240335760eef0fa146bf7b0c4b452163113936f6a594022ebfe86496c5997e24564deb89f09a59e11e2d",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Melody": {
            "Bb": {
                "scoreId": "63fac50b30206df5c52e0854",
                "sharingKey": "7d794be74ca93edf866430b63975646642f0ba73f9aed84cbf6615bbe3617e3e1af905b2ca7d3c5b8468b35a1aec3390db46ce17f88e0e2b1994ceca627f6c43",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Melody": {
            "Concert Pitch BC": {
                "scoreId": "63fac50c4e08dd4892cf5f77",
                "sharingKey": "2c53489f896e6f86e192d23133c0d5c21d5fadff390d90f7968431718d5df6c99f11b019f6a07b60115ee9cf378a8a0485b04cbd32516ae2abc799e45bcafe48",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fac50ccb614e7a85f1d322",
                "sharingKey": "eebd1ee616f66418790d86b7669e925758db62dc56ecd703aaca242227be1540615f568bacf0a0c296c4d4f3ef15dacd8eb14198cf8cbb86d9c0cb82f0ead6cd",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Melody": {
            "Concert Pitch TC": {
                "scoreId": "63fac50dac7007fc34068c7d",
                "sharingKey": "0bf820e9183cd79191db8c7c600d79ff330221117c3d7ae0011fced03f16142c580f9597cf76814d963927c1e8561d8c0327c2efda2f75a5122cad2be050a848",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fac50efb71844f2e19f4d2",
                "sharingKey": "d89fa9492a14b38644600a6983810ce8101314be65733b7a02927a21acf18e9de9a56717a59ad432706b0f389604b6661787ac2b9c173633556ef98a2264ee01",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Melody": {
            "Eb": {
                "scoreId": "63fac50d5390a70ce715b134",
                "sharingKey": "7338946bd5a9588932c202f3eb9f9e2d75b1f235e9f98d03b65f5433f0f5d04aefb18b8ef7e369811dccabb7f5794420415ea4cc9de70ac6fc3cb417cdc3e4d9",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Melody": {
            "F": {
                "scoreId": "63fac50bc28105b834180521",
                "sharingKey": "6b5097c165c9c6d9d125fa9aedd2da932ce850c017d9c100ce88eefa415fcbcb2510ed654b7e0e60d5aa61dc42c01fb1380afe4172df2c984dea33abeb3f8dae",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Bassline": {
            "Alto Clef": {
                "scoreId": "64ee4ef3e0f83305f0c5a7ff",
                "sharingKey": "463fe3121bde5e07611e7e33fe5d5ebc97bb60137c53c76270807429d5f987f57b53c3c96dfeed467d656275bb2cfc55692eeef130233a99e317a36591f9a80e",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Bassline": {
            "Bb": {
                "scoreId": "63fac768827cd2cabbf15cc6",
                "sharingKey": "c0dc7e07428fd3435b1a528fbb3cf30490413715f99085b4167e788fb98f5f743f3de13e230d75714ca2c0d81d447f20a6ab1d00f08ab6b3ef0f775545377e85",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63fac767026c55343670eb43",
                "sharingKey": "f4037ff83acd5d026bcd18e24b198047ce5f6df609005644d910526a44fb69070e62d8a40fbdf7508811c241dfc02369bc85d07ae2492513e8396cde656b43c9",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fac767ba7221492eb51760",
                "sharingKey": "cb4edc59f85e8f79619a7ef69aec8bf503e5b89a1bc11cd2d21cd2a69397e9d12fb63e18fde81980dca67ad900ca2f05760c4374c085e4637fee32e8165e3928",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63fac7637504c12d6ff31174",
                "sharingKey": "8db65fb917e6376d6a90917b5d91895e18c75185ca770e9eed2e4d7e69ed6337d88c4effb258e2c6b1c0b98922129ffafd80c07f52ff8883fded6e1c8542103c",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fac763827cd2cabbf15c7f",
                "sharingKey": "16e3d6494ffbebb9a9bc2f732e8317e1a966d6625f95cd2dacb8166b7aab82db4790bef100f1cc5e4ca7c211515ea53eabe5edcb49f0df6019036b381a9212b6",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Bassline": {
            "Eb": {
                "scoreId": "63fac763cb614e7a85f1f2fc",
                "sharingKey": "6630f117dde827f13fb58225462ce39b16722799937511abaa43799bf0236e22f3e219b330cd6e8af4c24ae9f5b5d402444e5225ced5be91d645a0dd6812c77e",
            }
        }
    },
    {
        "Beginning Band - Ode to Joy Bassline": {
            "F": {
                "scoreId": "63fac7680b26295c783ddea3",
                "sharingKey": "3469d0df0e876d408385de4fcafabf1a1e80f8c5453f7e45410eef94230f20cdea5c16c45619485ce72f55d5d2e7d7f985a126d3ef4acf05cf737ce9bc85f9ef",
            }
        }
    },
    {
        "Beginning Band - London Bridge Melody": {
            "Alto Clef": {
                "scoreId": "64ef9e661fe2f0d670e4e948",
                "sharingKey": "5630e8f4faff2099bdac1cd99f1192ce4baa77de3037d43a9882bf47d609ab19b5d9d95394216ef2bc7e86f353dcf4e6fae3f343ba87198e93709997bd0876af",
            }
        }
    },
    {
        "Beginning Band - London Bridge Melody": {
            "Bb": {
                "scoreId": "63fab949503c0084f13141ec",
                "sharingKey": "06ef458387c1110cfecb74db0e1444222df4ebd7784ad00b69bd3bbc02b282f9811237185b8855ef81457a6672f4cab133114a239ea88c0c85730c777652eab2",
            }
        }
    },
    {
        "Beginning Band - London Bridge Melody": {
            "Concert Pitch BC": {
                "scoreId": "63fab949f04dd86bca7e1f14",
                "sharingKey": "ff3f653f94bff2d44590a849df484b2ac02bb87a36e77e04e8ffce0ea719e96fbd1da583662f50399a1320c914616e8403d8a082b97a2415cf53eda38e432f63",
            }
        }
    },
    {
        "Beginning Band - London Bridge Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fab94b347443218fd0cfe3",
                "sharingKey": "2c6ab93da55f35f692936991bede123c38ab0da0cd0e4532281fc607367e2d193a08f0f6259e8d72e141ecaeb11a3f33dd098af173798344d93c5d17c165a7a5",
            }
        }
    },
    {
        "Beginning Band - London Bridge Melody": {
            "Concert Pitch TC": {
                "scoreId": "63fab94b4eca413f22c84938",
                "sharingKey": "fdec818713142694eb37f333257a0914f89ea31dc3571fbe8fbbbf64c662e7b913233f8896365b7d404127a95a4b89c6d8c07c110fcff62416e67f4d41a88c0f",
            }
        }
    },
    {
        "Beginning Band - London Bridge Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fab950080bd14d4060e4e8",
                "sharingKey": "f8b4af5082e8657999722d4eea3ceed212dfa1b4507da228077abf1f4febd130f7d831a34d035d4107791aaefa63f8011c5f6650389ce2f9ee06547290b07cd5",
            }
        }
    },
    {
        "Beginning Band - London Bridge Melody": {
            "Eb": {
                "scoreId": "63fab94ff17bf5858c2788d2",
                "sharingKey": "3cad0667cd92636f6628658068b5518f8f15f337108efdc72271ca220e3bc1cdc879c11aa8998cb746d022857619e1544a5e1d4800433538206a57450164eeb7",
            }
        }
    },
    {
        "Beginning Band - London Bridge Melody": {
            "F": {
                "scoreId": "63fab94ffbd3f5577396f1d7",
                "sharingKey": "3c0efcc3f84c89541511eeb8209eca83ecde8331f64076a7a23897acb2b30b049cf57ad48328ca5f136cfd1d63630fd9622536e478e16fbcad47820bd073c7e8",
            }
        }
    },
    {
        "Beginning Band - London Bridge Bassline": {
            "Alto Clef": {
                "scoreId": "64ef9d9f206b7ac4a24d36b7",
                "sharingKey": "e7e4be1921ac0a0bb5bdf057d640628984f9eeba4d56d68ae72c557f6e42ddc8e1aabb0a18c37f3777786e336a5fc4f6629e700051bd888201ac56822c767752",
            }
        }
    },
    {
        "Beginning Band - London Bridge Bassline": {
            "Bb": {
                "scoreId": "63fabf4285e03249551a2227",
                "sharingKey": "804f67593429c77143d6bd78cb6372c56dad86a7aa1b8c5855bf456389eeaf238030f5932a989748326c953e9a24b8205dd1c5a26c5e4ce3cda97f6502dad1f3",
            }
        }
    },
    {
        "Beginning Band - London Bridge Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63fabf415390a70ce7156558",
                "sharingKey": "93425687287aa5e995e269e5656de674d2744163e256a2f89a3afd88df47b39053f2f4fa8d5b9c03065ce4a91230d0abe2fc35c8c7e253049e3bc6284d26ab98",
            }
        }
    },
    {
        "Beginning Band - London Bridge Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fabf443eb3fd2d88e2b42c",
                "sharingKey": "20b1d8ca46d31e954c9a36e6786426fcad8d6682a6a93b15ec90ba4766519ce58a7e6840486ddb89772fcc30d2bcc6e3e852f0fbfb84fdc9da4a34d5c403a9f8",
            }
        }
    },
    {
        "Beginning Band - London Bridge Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63fabf45e8faf510cc357484",
                "sharingKey": "be41d7f15b796ad13d80c7eae21a2662760673967cb7c7d8610bad03fec823091befa4487943d9c3f23e64cb3d1dfeb52f81afec14ad31c540bd706d7ba9cc3a",
            }
        }
    },
    {
        "Beginning Band - London Bridge Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fabf41255c759f4afb0fc6",
                "sharingKey": "dea450e8cb8b631aa728a5c33fe73f6f89b8f884b1cb0b178a2c2892291566f19a7ab2bc1fc2d1ea45b8e007b0cf7919894bfc341c7edcf71dd7d796360fc3ab",
            }
        }
    },
    {
        "Beginning Band - London Bridge Bassline": {
            "Eb": {
                "scoreId": "63fabf434ad87f1309b96236",
                "sharingKey": "2793f0bfdcef81975eb36fbb1391ebd4d460ec2f54f9c6bd835e95b0ad60c8a7858ca2e954a2bc7f1f032ccecada0ea27ce747b5623e49a27f86b95e5c42e0b3",
            }
        }
    },
    {
        "Beginning Band - London Bridge Bassline": {
            "F": {
                "scoreId": "63fabf44e57db90e86e920e5",
                "sharingKey": "d346c84f8a7306b939102e9046bf49de589e37dea825938df6f4772684c4f714a1dbe047c446b6ae417282844b03f75c22ce00a2d13b070b1ac650b1cb86b109",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Melody": {
            "Alto Clef": {
                "scoreId": "64efa11141a5e556e5b40c66",
                "sharingKey": "187f99687d95466824479d55f283042db2438b2c36047923181d302c0aa4efcb4f4e329efa65548daf89ca69b9d05d56000d4afa1b373d948b468377e09a76aa",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Melody": {
            "Bb": {
                "scoreId": "63fa7551ece4d8e7bc9bc9a2",
                "sharingKey": "81345b5835425c637c56f6b537a9eb8f3c50216d56cccd9448f2b39c896a849a7db21d13fade12d2fb5d53ccd88dc8a2a43d80cd9275e31efb9e4269ad3b69bd",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Melody": {
            "Concert Pitch BC": {
                "scoreId": "63fa7551b1cc5665d25c4999",
                "sharingKey": "ba6d9957d783d6c47c689cdd407370d98e56f5ecbe475e23d2551a421eee23a5dd055e8f657d731c7110efa50e2830860ae35f7ac2869fbe55a943cd84af12a7",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fa75527d6c0db8dc9b5497",
                "sharingKey": "1e003036425858be411400e46639a283b46a904c72551afd22df8b57497d3050f69f5f6022cc3028d93ffb0f6fd2a8ec96b929769987856cf762feacce6bcae7",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Melody": {
            "Concert Pitch TC": {
                "scoreId": "63fa75561431f44e24cb5a72",
                "sharingKey": "7b4b85a9299df676192a3f469508b583323c694cbdc9771e105d01539882fe7441fcea0ebf2e1402999033ace3de7370c8891a5909f4b9d0d8eda2ca700fb302",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fa749e1e71c022e2750256",
                "sharingKey": "6ddc9d982442a2857a77ea6727fb842c2aca0f082d7772c17e848824590c7b1926169ae71fcc1fea9325d6cf6923b5fe5055eedce27046370f97e73f7da30c73",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Melody": {
            "Eb": {
                "scoreId": "63fa7556ac7007fc34024498",
                "sharingKey": "2ba07c8bbcdd5b470ad802734a616acecb986ad50e88fc3024b3fc689af6b8ca40120a801f34fd2e3e18080b3907fecf4f918de7012241b7dbba5c16d9e6f15d",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Melody": {
            "F": {
                "scoreId": "63fa75576c6e5ff8b9d17233",
                "sharingKey": "a755612fb2c537aa38eb59832760789b9a596f987f9eab6793a84a58d7ad2b6f8a7341a290920f1c4b05708e39533a81507f516ab855f9501e2b899080a16719",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Bassline": {
            "Alto Clef": {
                "scoreId": "64efa06f818b8598f4e41edf",
                "sharingKey": "77aa04db857a1307234e8dc59abf0740d54124425fdf997dd4cb9a5a24600b0a1d0f3b46ce465cef5d5838617a4904901482a3fce7fdb5095db46e02d77dd0d1",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Bassline": {
            "Bb": {
                "scoreId": "63fa85acbfb8216b6e2dc5ed",
                "sharingKey": "5e10feb63b9d69c241490fec37bf04693d55ab2d95f979020982ac0db77623a1cf8fff55faa4bb0e1ae376b68b03b16e3eefe6c0336acaa944c76f0c7ec7a48d",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63fa85a8b4b18faf181a7196",
                "sharingKey": "83df378ad56ce738bb0422673bf9d11f2e2eddefafb85f403c4dfbb5438a3ce3f39a8776084a5a58289249b406f4b4684ec9bb900e7f5003dab804b193d2cfef",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fa85a8255c759f4af7fabd",
                "sharingKey": "a5caa1bd789a059355ded728879a595cdcdf3e488b6f040f376d19c088e2a4ab03a1c3e441691946bd52633cc10bd2b43c842394299498f4228ba3fb5a966c49",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63fa85a984892fa874fe4179",
                "sharingKey": "69313689b54915c0e0018dc26eb3773746107578ef2f1f6dfdead7055a3ecd0561dfc924f4f442accb9c6abe74341f92f8a4ec3e7599e6316de21fc34b2286d1",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fa85aa503c0084f12e80eb",
                "sharingKey": "83258bffae7747a4fc9f5f54bdd46ab006beb4a84221286380728d39bfc54a25f17030ea8483976310caff5a922885df5090750e13c8112222d7dd0e8609da3f",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Bassline": {
            "Eb": {
                "scoreId": "63fa85a997f911f5b58bbb7c",
                "sharingKey": "97c4829e1ba6725276d1ace32f7f9f7e68b34a9c16d545df7de9c8634222328a90f8c2d105f456370973ab5ff13f7492f573dbc656431f3b0429cf80fd8e6687",
            }
        }
    },
    {
        "Beginning Band - Jolly Old St. Nick Bassline": {
            "F": {
                "scoreId": "63fa85ac6d4af8274317f2fe",
                "sharingKey": "80b6737ee08de2639bee93619053725128aa0fe69129163ffa69fa807f0936622197e8e5d57750b47331ad24b1082fa37de1ff8e2cec1e2c2cdd8c0cee3ffd9b",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Melody": {
            "Alto Clef": {
                "scoreId": "64f1df41c8888e6f5b496e65",
                "sharingKey": "6d6391a9a6f26c5ca6d4a47df51f5f28f28b2f687e7a5d2c229ed605f8356aa688c231e1401afa2c5f7c56a9e8ad7847cb37a4cf3472fe930193f04aa41642ae",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Melody": {
            "Bb": {
                "scoreId": "63fa606b347443218fcc28d4",
                "sharingKey": "05ea4691fc54c081d62ad9959758d52e8a73336bfca8904c9157906dc9601b30befce8452d6bfc84272a24cf1d23dc46b5f2d394455cbff801d2292cc7036d8c",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Melody": {
            "Concert Pitch BC": {
                "scoreId": "63fa606bdd474aea6e9a6e9d",
                "sharingKey": "75c1d254f06997cf67fe7704c296f35dfd51f20c0794523ed7bc1b4849044c4e8879b60ffbba06c6bb96bcd0efb642eeaed765f10eacee73137ff46de4e1bdcb",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fa606eb1cc5665d25b37b7",
                "sharingKey": "656a1d17b9ca5f23989a4790d894300c06f664c17e0045661a66868cfe2f7eaf50ebdc31035645222fb50d81cf7673ef428e0aa6dd50eae1d2656d2e4d494a12",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Melody": {
            "Concert Pitch TC": {
                "scoreId": "63fa606e6f460bbeae145fd4",
                "sharingKey": "26865a34b73f45dfd7d47b4af2f00b25b788a4fbe114e58f3537506357aec8e89f3a67e8936fec4c247ff8a6fb2668b70f7d6957993018e9b2ccd97784776b37",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fa606fb19b6ae2bef27194",
                "sharingKey": "146dab88a2b4b28af4fbca2a25ec61ac4196be11ec15985a2d08cc8dbe86841c1b30deefcdc2241cfec7d07c90ccfb09ae8f36dbe5ec417933c98220704052c8",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Melody": {
            "Eb": {
                "scoreId": "63fa606c53ebff1c707671fd",
                "sharingKey": "0e4b9693127b5b6c9e0a9ad9910804b8531748f08c94ec7b50f1fa5d93ddf7aa54a1011877563608c31d1fd21fb74f9aea42be161fab7028332bc73328e4f59f",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Melody": {
            "F": {
                "scoreId": "63fa606d56948320f96db72e",
                "sharingKey": "cd39e7bca470f41bdfa4082ce6473f849d271e53f3775787a9c4c16c4e87b353d8588f6baeee8db9eaea01835cd9c255a49cbe86fae0194aa905b3c7bd245cee",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Bassline": {
            "Alto Clef": {
                "scoreId": "64f1deb62088fea74618c714",
                "sharingKey": "b080fbd3acef3e7d862422c0141e0cec24494cabf7be38b8b2b2a2ae2ffa84ac993b1babff1549e90135f5d1096d90786f327204a1500ad87ab9cdb81c47fc59",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Bassline": {
            "Bb": {
                "scoreId": "63fa6739fd6707b995a8805e",
                "sharingKey": "bd5d759399accab8bd6d3142c74556e062d509f31930c0ad5b59ebf645893d175994f4eac71cc52bff7042b1a918aae7b09e016510931efce5b02e10ae4d871c",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63fa673b358117300d99dc21",
                "sharingKey": "dae270d5da601a8ce2bdc64f7cc570423c320d23310fcf581cbda862a3dd1f72e294c8ea26a1977c74efc86eb39e49e42ea02897676d8305e3e7e9a64ee0b188",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fa6739fd6707b995a8805e",
                "sharingKey": "bd5d759399accab8bd6d3142c74556e062d509f31930c0ad5b59ebf645893d175994f4eac71cc52bff7042b1a918aae7b09e016510931efce5b02e10ae4d871c",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63fa673c53ebff1c7076ca5f",
                "sharingKey": "b0f122cc3118f40ae3bd590ce41f80cdbbaf830b59c0cbe956114ad8d5ed1192e0cf9fb43135ee47ba97e424931dcfed2ce7e00fd86e2536cc5381354c99d1d5",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fa67397504c12d6fedfd23",
                "sharingKey": "6ab220672d820cf65af53766010e471661d7ff75676ed398b53ad24565fcfb01939ce85b332809420dcb41ac11b977c473faa10f89fdd7983c05158cc065255b",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Bassline": {
            "Eb": {
                "scoreId": "63fa673db4b18faf1818df6a",
                "sharingKey": "7a054a228a7c23a6ccb314b7a8f8629b690363da58ef8a118f9190f27685453c78e045674ca2fce6161620588b766cc3ee4e427510535be698c1ecfb4fb720b8",
            }
        }
    },
    {
        "Beginning Band - Jingle Bells Bassline": {
            "F": {
                "scoreId": "63fa673e7504c12d6fedfd8b",
                "sharingKey": "4bb10520b698761e1e004c75400d0356b2ff837b8b627ca35c53bc45793d102dea57b1b7f85421d289ea38224e23554b47f5fe6aab43e428a349df60b2417ee6",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Melody": {
            "Alto Clef": {
                "scoreId": "64f1e1e191dfe1ec5d4d1cf5",
                "sharingKey": "53700144dd0b5508a8f9e97a9b396010ece7c66c627c0b437cb5baaac6eb61e925a5e6389cc634e473447768c35dc425247c71ed9d34da6798be7e6cc0a33215",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Melody": {
            "Bb": {
                "scoreId": "63fba728e03a983c9546c23e",
                "sharingKey": "52d62ac59b07d34a163a4d4b76cadd101a496bfd20e3ae3b4c476a8082bd9a107ef0ef81e620e9d85400bd424341c928055e7b527073c9edf4fdbfab1a723b32",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Melody": {
            "Concert Pitch BC": {
                "scoreId": "63fba99c6e38d162c1658b55",
                "sharingKey": "2e998722b59a0d9967bb7bb5f74c15091d1e8762e91490134f1f698b66da81f19e6d2074d8779e16c80a484cdfd75497e42f4f70c9b97090f872061e14f44edd",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fb9ba3100e2ca605ed8604",
                "sharingKey": "7cb91dfead4c6ce44b8b3fdf35fd4f7b6ab68edca9c8eb3c118df23c890a2d17473ca3b03ec0aef52deb3c92126532c0a80631a02ed23d2d7df16b48aeef32e1",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Melody": {
            "Concert Pitch TC": {
                "scoreId": "63fba8114d0b56e9531ff5c5",
                "sharingKey": "5ede13bfc2b41608a8b15b386facde3e403ecb23f5a250e941534663b131a2e9c04f97df0a2516745f72915f3d7575af5170ca9e0182526a37820924cf8f4cc9",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fba812f3da4dc6cba1d6ce",
                "sharingKey": "930f4b8fb9d97dda9ed28bb8ff2703d944fdab5bc86094812c993235b2c17e5c20e0a0771463a7c0f44a2eab54dcc0508906e2a097fe558079f24231db8d26a7",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Melody": {
            "Eb": {
                "scoreId": "63fba811cac80a4f7ff7ad76",
                "sharingKey": "06dbad4eebe993024677b59f00a9f5d0ba574d77d271e18cc32d78a40e6d819b6c070e5ae3f8460988321f76df14a6b2df63f8e013905c1a8b172d6205d27595",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Melody": {
            "F": {
                "scoreId": "63fba81318c994e9ac94521a",
                "sharingKey": "c6e3943d2b0750e89045c73c0d28ccbdfee37c846eda2c8d55adf7fd9b736010b9edca632f1b24590dd5a0852bfa7c1d03fa6283392163d3c58702144414b95c",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Bassline": {
            "Alto Clef": {
                "scoreId": "64f1e12ee3bfd107a3c436d9",
                "sharingKey": "b32c408800bec193d17d6b40ce62811d5a6abc3bb9141098ae5dd3dd30ee96a79de115c774d8c69ecf494473da309858a8803f58e57678514ca855a36d3febbf",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Bassline": {
            "Bb": {
                "scoreId": "63fbacba30206df5c53a5f37",
                "sharingKey": "c31f2c975201ec44697fc9eac170a06ee89829441ed84ee8a3fc5bf099b248259d547cd136b016769673db9de0e5d98bc1a5e94808655915d8bcd230e79c5d3d",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63fbab1f7421e312cb5b02da",
                "sharingKey": "4c8cc4bf6f17746ca480e951320ab4e09b34be0b319ce444a537fec8a0aed650b01c07a2656d9cb33f64bc2cd4d3e5f7597bca275d69bfcdd67ffc5887aa1d79",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63fbacbb7823f691262f6648",
                "sharingKey": "175fc1ef86d6b4267d21c5f97a3772cfe812528f538ac1653e6d8c21bd01f180d21b3c5ddebbb4409082505292b11db34d061629d2d04026e76805a2abcf7bb1",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63fbacbe0c508266c8640a9a",
                "sharingKey": "66d7d1b2fd6e2937fbf07effbc71e4b1a7744ce537d1b6164b5c6eb4e1b3d89a17986c98ab0e81733e4f072213677f9be576a6f636aa065d57b277e05c45cf84",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63fbacbf0b26295c784a1a49",
                "sharingKey": "66428d89b42df8436099272228f8d0a746985e737024add37b2fb17c8e2e6ebc3a75a51d8672f03d64044ea345bf102ed477e608ba5f2535a77f07f6ff73107d",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Bassline": {
            "Eb": {
                "scoreId": "63fbacbe65f99c0e2758c424",
                "sharingKey": "04781b730e70221067edb8da33942b11ed178c80b73efccda609ffa7a2e11b10e755be32df9a1110c488148977de6dfca93fbd9d885971fd6e596bb41ea64258",
            }
        }
    },
    {
        "Beginning Band - Hot Cross Buns Bassline": {
            "F": {
                "scoreId": "63fbacba537dd1ccc12e08d9",
                "sharingKey": "1ae2561fc55ae175f1f89eba08be5d9a394e886a99e4b2f32569138fba2ef67718aa991bb9939fc86616f55b704dad2ef7408a334e28ee6d8db0f4253f5d4b4c",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Melody": {
            "Alto Clef": {
                "scoreId": "64f1e4a80771268f09c05af5",
                "sharingKey": "868fd0f7249fe5b9695830b1a4071f0d281d5d9179ff99bc7f1f707cd47109a496dd0e6ea0d2bacbc4accfac19881b9ebeb553364433d2bb4fe806c2b9da307c",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Melody": {
            "Bb": {
                "scoreId": "63f82996c9cf64b27661d900",
                "sharingKey": "52db54f6ad3dd54194c8ed42e11ead50ee5675c65816c7d9ef89471c033747398a1dbbd9d66a5026132bb549203d52bef98ac873d4d822f592eb37136da7afaa",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Melody": {
            "Concert Pitch BC": {
                "scoreId": "63f83258590aeb6fc8ce2d91",
                "sharingKey": "769a978c12020f913c797887edb0856fa960262223e3f02288d23f473c0a096a8bfb2f2adc6baea4802c1419009bf289d56bfc3f1e8d7e04846f16b6846264ad",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63f832c2ef72f72ad6dad546",
                "sharingKey": "ac087c0e2a50062c626f9558f14fdaaf31126e61288b4865ec3f4e119850744aa27046893f06e2621593a6450b934bcc21dc9a2bc46ec285396cfb660a45f164",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Melody": {
            "Concert Pitch TC": {
                "scoreId": "63f8292cf97d5b4404d70161",
                "sharingKey": "478d83164577d52a0088cee70b70333d73184989ea7779d5fcce9530c6af444912a324f1132762f0503dfef4d7ec6d27da5adf7f7f9333241b55f009737d9508",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63f8279a7910ef4071eee11b",
                "sharingKey": "b1839ce2ba0c7685583be46368be33a557ed4cfd4b496f823bb2e6266f6f74f7ca1bc65558e28239fb17f431a31ffc154db5d8cf352656eabc63fe19790bc32c",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Melody": {
            "Eb": {
                "scoreId": "63f8314954057979269e3a71",
                "sharingKey": "1fd24fe8fcd420daf03f8035740ac21255950611e9b01885143dac840c27498be88efb03949450f1848497567c6416b32e1e37e18633a036e3770f69457930e2",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Melody": {
            "F": {
                "scoreId": "63f831f5fe9d5ce40cd87446",
                "sharingKey": "22587fbaebaaef7750503b073f71f9457ccaa68c147c00cef83b4f6cf44d1fb2747ae57b854fdbb6a4328676ee0118eac241af4c04c2ea316ca8335d0ef0df4b",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Bassline": {
            "Alto Clef": {
                "scoreId": "64f1e40f91dfe1ec5d4d4534",
                "sharingKey": "84db84b56289b2888036bb37a607fb6fb75eadfe8649c4576e7d3247744f8df4e4b6f403afa4b96039861da97b8fcd4d3a21fc357506aeb577ce3b232308a844",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Bassline": {
            "Bb": {
                "scoreId": "63f83cec9d387f8467afe1c0",
                "sharingKey": "3c72f1b9e060e2ac444bac1e89ed19ca5db41f3e20abeb8333c8ed91cd33039f12c15c1f10c1d8255ff934b7ffddf0c04e50cf6db25a3b31768b966da0d82b43",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63f8355f9f1e7ff30571fd91",
                "sharingKey": "6bfe3e0c1dfe0716223e9e0e314c95db6f0a4b49fa124e638669cee20f03a9cd9d1709e7bc67b6e10739832ff2a332aa643052daa0c5fda480cc586031731bde",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63f8279a5dc7feaa5144a409",
                "sharingKey": "a491bb39fc52287e8ffee0da8f010711f180740cd7f6fb28a13162d1d1f46366b4c4d1e9aa1caf67330db2782799e00a4bdc6270faaff9a4b407da439bf34c5e",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63f83bfb55f02774c0652801",
                "sharingKey": "0ea70a6852248b15b9179010b9eaf98e2a5ff4bf884eefcec6c75b8b5a017cfde1dc13a8f267e5d796a8977e8f94b321168f9addf9701612f181d731f7dfb846",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63f834b15dc7feaa51456d35",
                "sharingKey": "ee7c221c5d10c98da9b0e0bf4de0e7b3410127f6be63dcfd3982c93b496b740c8706cc478848e3eeb54aca4cd80408015f540b78377ff6439447ce0cb03f8e22",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Bassline": {
            "Eb": {
                "scoreId": "63f83db75f76d5a40a40d9ee",
                "sharingKey": "2abf0bef4a404bf1277a5fa8b12b5ec6984e39e87e1bc4252d048e714c3e878ccfcbd6846f8b63048152093ed85175ae566961232dbe63856651d433f862bb8d",
            }
        }
    },
    {
        "Beginning Band - Good King Wenceslas Bassline": {
            "F": {
                "scoreId": "63f83e22219275f55cbc6cfd",
                "sharingKey": "182ac29bc95ec4072876be6ecce884b03a182fa38c409359c7c49f79ff05adff7836e9d84431de1925610ce04116f39fda27222df29300d90672c2838aa31be0",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Melody": {
            "Alto Clef": {
                "scoreId": "64f1e60d7b1782261a51b6fd",
                "sharingKey": "8eea8e941fe8168a8fe84df447f192d4aafa79471e1384dcb1b7f662b5e30590ba664d5931aea56fa745b043ad9c9ea8061c6624690e51cc8a7eeda4836bb30b",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Melody": {
            "Bb": {
                "scoreId": "63f7beae910a80acea177441",
                "sharingKey": "9b722c5e75519d4b53f8f6ad7acbd3c263482ce2086126dc6f43334706aea8b7705d5d8bdcb31ebd33c6982793266899eb6785c0b5c91ad57c79e34097e62edf",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Melody": {
            "Concert Pitch BC": {
                "scoreId": "63f7c1e59f1e7ff3056b2544",
                "sharingKey": "fc9ab9641a032bd73371326c20848350e8a5a7bd4d28bf2016f3a0b699e9fd299f452a1e79962281aee66e99ec6c588f0fa79e2f7c2f5d54bae374c889d5a95c",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63f7c234eb49319bbf17305b",
                "sharingKey": "3acf631fafc751bd72ef6964e30417621c8e5450ea21606d82f31a11a8c60d92037ca71fe11c45b31cd27040d44e117aeac13d5805cf51f1e5dc16e620389134",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Melody": {
            "Concert Pitch TC": {
                "scoreId": "63f7bdcd0893cd9767914950",
                "sharingKey": "9fccff2d1580d1718281726410eefa56cf171d57a75d8e39d62e52749817e8cbce04364115b9f26c9596f851ac58a81c84917033f5ca231a44bcd93c7a50da59",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63f7c0c26d4af82743ef5f4b",
                "sharingKey": "20488199137b983c0e829d65046dfca65fb4434670d8650e9d1f978934044efa71786ba9866eea7bbe21d8947d2cb0d9e4bbc95d93c41fd093ea8e0b962561ce",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Melody": {
            "Eb": {
                "scoreId": "63f7bf516d4af82743ef4644",
                "sharingKey": "0324efe1a70dfd5a3ab0883046e9302fe3203f384494d699d056a68146cd28e91dd8c5e2b82c0353e6edd6027bc0ffe5439b56ae65903f899414b57fd115e050",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Melody": {
            "F": {
                "scoreId": "63f7c0306d4af82743ef553d",
                "sharingKey": "3908ea877bda350009528ea798f9fe2c156b2f3bca11419ea23f5d0d0e93dfd3a0485b355a7a971ce0e1275f00fb3310a1411bd509412748e5c947c964fc459c",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Bassline": {
            "Alto Clef": {
                "scoreId": "64f1e66cd0cbcbcecf6d75a0",
                "sharingKey": "dea762c5660f5a1d8c49a9c398d004f8958666fd5308e720277a3c9d81a52e0514ba89d82c6451633d0ef99bbcb07f037543291c9044cfba266b546a024556c9",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Bassline": {
            "Bb": {
                "scoreId": "63f81a7563f4e843f19c6722",
                "sharingKey": "b783488d30eab6c190ff13375229f274bd38b1fdba15983ce2bfc47088eff882453ffbd84e2d68cfb19a140086548625a43cdd4fd6ca6f9f19135100b3768b97",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63f8188a828a059f131b9c4a",
                "sharingKey": "62b2a097c18b1de4d2eff3dd3797a86672f2fd11b6fcc93f714aaaed7d08eb035d37f204c8aa7bd1efb80e11e71626bea721f3904f31887ac86b0d0494614aec",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63f81fa0b0734a669b6e800f",
                "sharingKey": "e3767f2ce3f9a0006e9bd401ef5f7f33d2932f9f8f67865e343fefcfc6d717522e724b5ad3dfc947b055a753ee8ce39aa2fe3af48ebdcbb03ba47ad7e27b3ba2",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63f7bbcbfc872e3f51be17d4",
                "sharingKey": "58227da35f7e0a05f55a87f0bd21098c2e17ce8d449968420a03393c488014b344cf5f619f44de47db49c1bed071086f0b400adf3ebd6b0c93b2f0a57bad00d8",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63f820bee290cbea2d30967c",
                "sharingKey": "758df30c684c6ed57572773d2c2642491706b371c311645051b6a8bd6ea04f8833d0d6310242366ba4b1591bbabee2ef6010c0cd43b5a446dd677fa0df4d4212",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Bassline": {
            "Eb": {
                "scoreId": "63f81bf654057979269ce7c7",
                "sharingKey": "79388c4a65f01cbbda5175f19c84d62029ec427154c48d4d17a33a3984e29590fddbff9115575cfa1a59ca33e3ad34c4d146b68ed93c816101250d67cdf02cde",
            }
        }
    },
    {
        "Beginning Band - Go Tell Aunt Rhody Bassline": {
            "F": {
                "scoreId": "63f81e45828a059f131bf9f5",
                "sharingKey": "29b322ee4b81489f2533070a09606ff10145cb04e8bae6c1474496948c3b7f138ac4e9498b19eefd05665705acde76f63549c067d12f22f7b942b2441032f33c",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Melody": {
            "Alto Clef": {
                "scoreId": "64f1e86ec5eb175cf1bc2ecd",
                "sharingKey": "d4ce2db90f7afffd4e295aa51e170c3e1fbfe448badabaf0fc16773d862432e0c5d6b18ef78d17aaf78d594a3b8c86d9b3d40ea657fe22b1ae0f5eaa7b5189a7",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Melody": {
            "Bb": {
                "scoreId": "63f7ada2c2352681b29e7ab4",
                "sharingKey": "a8f79026f55a5724b3b3e3299591564c0bc5b3c67190a2a95a950826d514c3cae073ddae546f4eca9c7371504144d464d9c9ccab2e8953a41f3209e98d86d3b0",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Melody": {
            "Concert Pitch BC": {
                "scoreId": "63f7af4b999588fa07f85c0b",
                "sharingKey": "d0b5a06fa073a2fd01748528941e49e425c87944ba0fd3a2e661078ff990961c0b757f93bddbe4a91429f6556021df65422d16428a5e1d053fd636ad22514e9a",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63f7afdd999588fa07f8652c",
                "sharingKey": "ca252c3615a0a9d376f0a55eec96d4796c4018bd3c1f117beb4411f1f0455734b25ac4fa9e6c3b01526c0095573bfbb02525a69e688526a364972866c2bd7c40",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Melody": {
            "Concert Pitch TC": {
                "scoreId": "63f7ac92a9d96cb0cd5b9d2b",
                "sharingKey": "67ee0dec742b9d3743d3dd323de2575e8cb6c3c45cfbf9ee25009b88f193236d6b683aa4d0daaf3ac2d73b6f75f68a6021028b98141ec19784d97918ed48d3a4",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63f7ad1a828a059f13152530",
                "sharingKey": "27540d039c01f1b27997e11283e971768bf30d3c4043392e878b6e5bf82911df0951d09d6dc996b2f69d5e474a1534335aaddb65cace5926b851efed41708d43",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Melody": {
            "Eb": {
                "scoreId": "63f7ae489e89e7a3d2402826",
                "sharingKey": "24760508b8d0f2792885690a3a92a7b26fcf5bf89797499aa1e4be692756709dccc5b93053eb5bb039f637770ba6cd59d12e0ab9c2aefed15243d01c85b86dda",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Melody": {
            "F": {
                "scoreId": "63f7ae98590aeb6fc8c62958",
                "sharingKey": "cfd90a249bb5afb8533ead2930f49be750e9ee78ef858bd88cace7feb61771b1517c276fc567a22fa90f6adbf09e09df8ea7df002d7671c71304b2b55defcf14",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Bassline": {
            "Alto Clef": {
                "scoreId": "64f1e7f6c5eb175cf1bc21c8",
                "sharingKey": "44c8d53ba06a99fcf60d77f400f7befc890fb8a0ca35a9c83502867256f6b18c7ff0d908fb850e4ef5e7d9ce35daee53f859337de88bfc87c4e21f6c140e3a09",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Bassline": {
            "Bb": {
                "scoreId": "63f7b168d0656657d0f2de7d",
                "sharingKey": "f32df2aae27c747a61c663d933dc30a8d9eee3dba3d7a5759db326cbed5f42dd89877c786b5bfd7f5bf1cbb6f1f74ded717bc7908bf6bf9d9c76631b54ed900d",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63f7b982f97d5b4404d04ff7",
                "sharingKey": "510975003832bf6df981ed99cc74b54885933dc201dc4d284194100d1b9ccf79b977a1b2319ce077ba95bf29386190cec7e0990ee02207c80ed832697beb6aa9",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63f7ba27910a80acea171c9c",
                "sharingKey": "6be726c35e48beb90df901ec1ce2c2004233b3fbe522465a814c0bb586a27d7ef9dc3630efb9bb4bd86bcf503aecb7866fdfb80b84058ef65e011fafc230ab66",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63f7b0a758da9f4799094b08",
                "sharingKey": "519308887594c43626d5c099bda15f4503e87bdc293aae411d7ea0ced470fd5cfbf6cd7f01652e64b9fd5d804f6613df1026b53ba2a8b7679fc73b96eee9327b",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63f7b1269ce8bf910a7f0a75",
                "sharingKey": "be461811c3cdda8614df8b6fee898917cba261d69d4b6f50f5503c479e6d36b5048450c2f9bc37bf4280ebe355b41d061323e9da19874014108b329ecd23d3aa",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Bassline": {
            "Eb": {
                "scoreId": "63f7b1f5aa56c2f609f8f6f9",
                "sharingKey": "882e6d4394380bcc37c4ad880a87ac8167fa8152ba9f368b2dcc4879baaf3f07c347735757bd593b315445aa6745c650392d89906045d0653f5a1814dcf1ef9a",
            }
        }
    },
    {
        "Beginning Band - Aura Lee Bassline": {
            "F": {
                "scoreId": "63f7b91acf40723009949d7f",
                "sharingKey": "46d427acf21fe76e22925f73ac0da8320399f6c64096580c8c207b72dfa85df4f2df9fc36c108a845a82b534cf01aefccb6abc830e52e8cac5c2fc69f0233e50",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Melody": {
            "Alto Clef": {
                "scoreId": "64f1eb02c5eb175cf1bc57bf",
                "sharingKey": "5ad118a51979c70a908492b48a88e21763fca949ca94ac3b5acbda4fc8a9c8a7cfe9e5dda963420935e24edd5577a3ea77ebba6b2cd8984abcc10f87b0c71f33",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Melody": {
            "Bb": {
                "scoreId": "63f6a7c952f1e013c2827128",
                "sharingKey": "a76d95642af0f9f208e6f4e45ece1ebb43162b7a20d4d150d212757e7ec8f367f1d8ef096fe7d7ce8cf0863f5c8d8f6b49f729f4a570641943ce61fbbb790732",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Melody": {
            "Concert Pitch BC": {
                "scoreId": "63f777f27910ef4071e42a80",
                "sharingKey": "258050582a20e233fab9f426e156703c5884eb9f5b277f39fb3734763633a8f4089a7a3ef965050b63599c55b2daaff11022111097bf00c256e16307d1c36620",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63f77906910a80acea1304c4",
                "sharingKey": "102367298fc311fd62ce51a3520d25eab91d876583e7f66efbb783b54555e579b5385b67750e5e5667706168457618acadc745c66351d8ab682bc689156ae6b9",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Melody": {
            "Concert Pitch TC": {
                "scoreId": "63f6a66ae87eddb9786d6c7a",
                "sharingKey": "6696584aa17c01f1f9d1ae47ab600b8b275918ec4d423f275ab38bfda9f8291b63e74acd22aeb5f4ddcba6ebaddbff12579918b7848bf9996bb41175cb10b0ed",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Melody": {
            "Concert Pitch TC 8va": {
                "scoreId": "63f6a3b0c0509386564ddfa3",
                "sharingKey": "17b3d94bb799ff15e71ddc477337384be3fab70d04740c3ea55dbf20f0d0f7baf60bb2552bb87b7f0b1317a5bd46d786546d942092488659863bf1c2da326354",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Melody": {
            "Eb": {
                "scoreId": "63f6a8f9694999e7518f4e0a",
                "sharingKey": "75215ed9be4d076c1ce5af1cef0113f9367f62c62f1c829144f7e2b613f7afdc68116db72149359c6e6ff25716c3a80a8ae0ff5b2173c7e35059dad15a825efc",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Melody": {
            "F": {
                "scoreId": "63f6a87e4b6b297304b59ed6",
                "sharingKey": "eaa16bfc701f798db059bcb2620dbc935d3d436c8dd2c1c6b8384ed8cbafef4cef971f1cce89a7694964f17060d010d5969dfb12bb78ad7b4e1df044b4e2b489",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Bassline": {
            "Alto Clef": {
                "scoreId": "64f1ea5901f1338c1f759851",
                "sharingKey": "28ebc823e8b4d984a1a4ff4d9bf8457a209417061550a554489de3636eab9f72679694896496a647e8c4b2b0f464eeb1a0c965ff4e92847e07fb79956fdf9e23",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Bassline": {
            "Bb": {
                "scoreId": "63f787ae03490817798dfd16",
                "sharingKey": "724d966cf25e81177812d53d9fbafc30fe7641e51c1564ec9733e38cbbbb74216462069ddc726aab506b505d694d2fcc2afe8744aeabf5a752cbc44b4cd8542e",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Bassline": {
            "Concert Pitch BC": {
                "scoreId": "63f77ae19ced37e2752fc48d",
                "sharingKey": "d96df01af86f395279485a9bdf3e4ad4e989df5c9de5c50ccd0f9a3c6cd4ea5b6cdfebc4a127586bdb4e66c5f6e0cf046e8fde4e832bd6f30b5f712ff2efd04d",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "63f77ce19e89e7a3d23d1241",
                "sharingKey": "9992f81f15afc011b23923001aa30cd734dda9ce833e47ab274c8120c0e741275ccfdc0c607aed50e57984fb74f9f2623be33568c75a925960ce24995cfc7131",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Bassline": {
            "Concert Pitch TC": {
                "scoreId": "63f78811fe9d5ce40cce0718",
                "sharingKey": "ac297acca822d58250bc48a096b14adc3a54551c11427df7d5e3c25dfc8fc88ee5d283279f5a5fb5162619259192cbcf6d301dd67240ce977f4264a730cc01b3",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Bassline": {
            "Concert Pitch TC 8va": {
                "scoreId": "63f77e5395e441f70f7dabc0",
                "sharingKey": "a05272464b011ecf2f9303b32a259032485695e69fe6b81e8df6ad21e87e9a2fbe4f6cb3d38c805862e5d6a7e5a28b0be27955925568acd24153d6842fa5a508",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Bassline": {
            "Eb": {
                "scoreId": "63f77fbf878820c543d4e852",
                "sharingKey": "f364a63183be1d3cc9b5e9989f0b20100beaec728c1a47b601bfae4dac212c45c7d8f16776666046a3e3981cae9c6ae9197b94f55b5b220b26b8dd01061fe59e",
            }
        }
    },
    {
        "Beginning Band - Amazing Grace Bassline": {
            "F": {
                "scoreId": "63f785216b9b0f9db7270f66",
                "sharingKey": "9048a6227780702cc2e153a62ca4e0f65d7f83a1f1ff2919f57fbbdeb9327f0a41b72cb1aeb9ab33ee721aa466f825ebf592191ce4088456ee6a5edaa796836f",
            }
        }
    },
]

for piece in from_xml:
    for piece_part, part_trans in piece.items():
        if piece_part not in flatios:
            flatios[piece_part] = {}
        for transp, flat_info in part_trans.items():
            flatios[piece_part][transp] = flat_info


def update_site_forward(apps, schema_editor):
    Piece = apps.get_model("musics", "Piece")
    if Piece.objects.filter(name=data[0]["name"]).exists():
        return

    for piece in data:
        for part in piece["parts"]:
            for t in part["transpositions"]:
                t["flatio"] = json.dumps(flatios[part["name"]][t["transposition"]])
        create_piece_et_al(apps, piece)


class Migration(migrations.Migration):
    dependencies = [
        ("musics", "0018_seed_more_music"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
