# Generated by Django 3.2.11 on 2023-09-18 18:51

from django.db import migrations
import json
from teleband.musics.api.serializers import *

data = [
    {
        "name": "Beginning Orchestra - Bile em Cabbage Down",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Bile em Cabbage Down - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Orchestra - Bile em Cabbage Down Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    # {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    # {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    # {"transposition": "Eb"},
                    # {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Orchestra - Bile em Cabbage Down Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    # {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    # {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    # {"transposition": "Eb"},
                    # {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Orchestra - Go Tell Aunt Rhody",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Go Tell Aunt Rhody - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Orchestra - Go Tell Aunt Rhody Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    # {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    # {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    # {"transposition": "Eb"},
                    # {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Orchestra - Go Tell Aunt Rhody Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    # {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    # {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    # {"transposition": "Eb"},
                    # {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Orchestra - Good King Wenceslas",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Good King Wenceslas - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Orchestra - Good King Wenceslas Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    # {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    # {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    # {"transposition": "Eb"},
                    # {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Orchestra - Good King Wenceslas Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    # {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    # {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    # {"transposition": "Eb"},
                    # {"transposition": "F"},
                ],
            },
        ],
    },
    {
        "name": "Beginning Orchestra - Hot Cross Buns",
        "ensemble_type": "Band",
        "accompaniment": "accompaniments/Hot Cross Buns - Accomp.mp3",
        "parts": [
            {
                "name": "Beginning Orchestra - Hot Cross Buns Melody",
                "part_type": "Melody",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    # {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    # {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    # {"transposition": "Eb"},
                    # {"transposition": "F"},
                ],
            },
            {
                "name": "Beginning Orchestra - Hot Cross Buns Bassline",
                "part_type": "Bassline",
                "transpositions": [
                    {"transposition": "Alto Clef"},
                    # {"transposition": "Bb"},
                    {"transposition": "Concert Pitch BC 8vb"},
                    {"transposition": "Concert Pitch BC"},
                    # {"transposition": "Concert Pitch TC 8va"},
                    {"transposition": "Concert Pitch TC"},
                    # {"transposition": "Eb"},
                    # {"transposition": "F"},
                ],
            },
        ],
    },
]


flatios = {}
from_xml = [
    {
        "Beginning Orchestra - Bile em Cabbage Down Melody": {
            "Alto Clef": {
                "scoreId": "64ee171a069618a0c0aaf010",
                "sharingKey": "1f51222204ad37fe0f037172a4fc422b091cb47d4953158fe463b3ac918294ff82a912babbc0e93a240f3f5d4a79d231128002860bdd1897d3364e5d3ce76c37",
            }
        }
    },
    {
        "Beginning Orchestra - Bile em Cabbage Down Melody": {
            "Concert Pitch TC": {
                "scoreId": "64ee17071f65ea105c22c307",
                "sharingKey": "31119f8dec4622041223de3e0d42ee52f3c0deeffe7ac9cfc8869f9e67a9406d7903f637cf2c8edeaecebd486d7e4c9dd4ed9d0667c8ccb6efb414f7566eed09",
            }
        }
    },
    {
        "Beginning Orchestra - Bile em Cabbage Down Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "64ee173fd126671ae4121160",
                "sharingKey": "3e86b653501c605836f0c95b5c4e3de1edc2f810fb6079527a544b1b514e6978b83f8f22167d0887e100b20efdb66a114aea583fa513f8c59901d1769c2f3990",
            }
        }
    },
    {
        "Beginning Orchestra - Bile em Cabbage Down Melody": {
            "Concert Pitch BC": {
                "scoreId": "64ee172f2883844847d63b66",
                "sharingKey": "4ca5213ef2c07050ee5885f02da5c28c5dd801bd660baba1c4cfe8adefeef55191aaed718df2aa873c1c66a5e5753374de6429b2f400d4410a023cc7fc6a2bc5",
            }
        }
    },
    {
        "Beginning Orchestra - Bile em Cabbage Down Bassline": {
            "Alto Clef": {
                "scoreId": "64ee171affc1ad111166c5d3",
                "sharingKey": "15bdd659ed213d2139bf36d8456fa293e24b98f5f57279434de64e1c7aafda70791fb32198b56c005ccecb5802d265047ee6abdffe9247258e33496c51e1c539",
            }
        }
    },
    {
        "Beginning Orchestra - Bile em Cabbage Down Bassline": {
            "Concert Pitch TC": {
                "scoreId": "64ee17070579d3d022012e26",
                "sharingKey": "9abbdd1772f31c26d22ea713f15db2ca9872a4408c695557a14134684a66778fa1649f81f8e8652f70ebb7be211efea3c76f39490c95fc4b6550aace6b663413",
            }
        }
    },
    {
        "Beginning Orchestra - Bile em Cabbage Down Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "64ee173f20ad411b169aa416",
                "sharingKey": "7eda883949a75807f8c118195bb3eb0f0ca73deb96971de88fa867be35d742c8fea0cb6378e1c572e510d5b8542d13aefc241a31809e5fcc6b8421d727581fc6",
            }
        }
    },
    {
        "Beginning Orchestra - Bile em Cabbage Down Bassline": {
            "Concert Pitch BC": {
                "scoreId": "64ee172ff43f9ddb80ba12f6",
                "sharingKey": "51e57678f678d9fb280fa81c056258bc910daad8048155905108d7cf209dfe052c58a7ed442032c94bd34ebeddc4cfd97920595a4a2f35a2471cf3dcd439c270",
            }
        }
    },
    {
        "Beginning Orchestra - Go Tell Aunt Rhody Melody": {
            "Alto Clef": {
                "scoreId": "64ee15dd1f65ea105c22a9b1",
                "sharingKey": "21eab5638709f4d6331fd136af6af244d50cde720b836cf5f532a0e5f28dddfee346a4af45cca378c24e8cf1f65a3a0f24e785c83b85c86ce5936820d48e77d1",
            }
        }
    },
    {
        "Beginning Orchestra - Go Tell Aunt Rhody Melody": {
            "Concert Pitch TC": {
                "scoreId": "64ee15c61ca3db74f91fac8d",
                "sharingKey": "fd8471fbcde8d9331b993a58205b8aa3a34a6cfc844640822abf724626c8a7c2989508a0e847f24634a1e98284b06e305231ed19ed9fcee396b4637e0c69f10c",
            }
        }
    },
    {
        "Beginning Orchestra - Go Tell Aunt Rhody Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "64ee16029e2325cb3bb4c6f6",
                "sharingKey": "003f1f275678d9ecd2a6d9ff7fa89899e262f3a1c3e33b42f7f574a1c6d5d1c5dbee105ec531d43dd2d33729538249c92cbbf37bb71257d78b21400e67e0a6d7",
            }
        }
    },
    {
        "Beginning Orchestra - Go Tell Aunt Rhody Melody": {
            "Concert Pitch BC": {
                "scoreId": "64ee15ef8bf71b591ce948cb",
                "sharingKey": "4f1f1d51422facf31fb94ab23c2ae776934f9162fc4ef607edfbe7998a62fa2c125135fe69847de152c017b63aaf6b48db2e907a8e28099d579f143096d6b851",
            }
        }
    },
    {
        "Beginning Orchestra - Go Tell Aunt Rhody Bassline": {
            "Alto Clef": {
                "scoreId": "64ee15ddd126671ae411f48f",
                "sharingKey": "b670061380407743d4bfd72defe6daa3aecfac0f0b8cd15cbec97cdb2d69637ba8c0c2fd5c72db9a48c6384a91435bdc13b0a765a9afcdc9e92334db657b224f",
            }
        }
    },
    {
        "Beginning Orchestra - Go Tell Aunt Rhody Bassline": {
            "Concert Pitch TC": {
                "scoreId": "64ee15c661b1b5967044a5b3",
                "sharingKey": "ba69f6c84dccb222637054d58216bc5da16c849117f27285d30abb97d03609035ca4f5244de8fe80e1a7e4c1211d1a0055434ed811faed460a6981e1c1ebb029",
            }
        }
    },
    {
        "Beginning Orchestra - Go Tell Aunt Rhody Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "64ee1602dadc9877c42f4f41",
                "sharingKey": "98ffe0b4eca4bbbc8cdb040cf9c5f89ba06ba554adc47a03c8cc23959684d2706ed63c7eb90dd0c6ff9d5564944fab968e746ae0785179cd113bde9eb2e56129",
            }
        }
    },
    {
        "Beginning Orchestra - Go Tell Aunt Rhody Bassline": {
            "Concert Pitch BC": {
                "scoreId": "64ee15efffc1ad111166ad19",
                "sharingKey": "aa058d918b9951bab2912a7c3090008f4419d2a4de43ae460f0463fa9e44fd95aeafe2ff746ea46be58506f45c1cb108dfb146c4f91217ec4e58b13a0de594fa",
            }
        }
    },
    {
        "Beginning Orchestra - Good King Wenceslas Melody": {
            "Alto Clef": {
                "scoreId": "64ee15611148b0fd6a759452",
                "sharingKey": "fa4dd500c38de7ad6b450df6fa0a6dd63b7e156dc71cb87562d0f0ae167946e1b22c48bba905d93cb2be5127206c38e17705acf237cd434ffdf163732b3295cc",
            }
        }
    },
    {
        "Beginning Orchestra - Good King Wenceslas Melody": {
            "Concert Pitch TC": {
                "scoreId": "64ee154dd126671ae411e8d0",
                "sharingKey": "05a205dc085c6b6522415cd1bc292d7c1bf90370e8731b9f0eb2bbc5229b12399c1adda03a44bab2881f5cf7a5a7b8060493aeeb28abefcd45aff7a77fdee45e",
            }
        }
    },
    {
        "Beginning Orchestra - Good King Wenceslas Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "64ee158b8bf71b591ce94005",
                "sharingKey": "4d6cd1173e5dd3a0b8d2f6f98abac461aff6e84ed691a18606e992a1aa87e38b7f99fb42cf194a9e95559cc4f2bf408470b349b7ce8c39116a96821026335feb",
            }
        }
    },
    {
        "Beginning Orchestra - Good King Wenceslas Melody": {
            "Concert Pitch BC": {
                "scoreId": "64ee157a1f65ea105c22a221",
                "sharingKey": "e976a44d4e30805afb0fe67508977566c141263c16809d5da373c46d985dbce6924612301bfa953627ee643762e9be221c738e7b160533d33aeeb178816fcf73",
            }
        }
    },
    {
        "Beginning Orchestra - Good King Wenceslas Bassline": {
            "Alto Clef": {
                "scoreId": "64ee15619e2325cb3bb4b9af",
                "sharingKey": "9062326e95353d1609c83beb42051cc2cd5e64fc78194756e5efeaeb160bdab8be202cea8bd44b5ca5f07318f5e766bde3f27f9adc67cfdcb558d5220f973b2e",
            }
        }
    },
    {
        "Beginning Orchestra - Good King Wenceslas Bassline": {
            "Concert Pitch TC": {
                "scoreId": "64ee154d8bf71b591ce93b45",
                "sharingKey": "b522e86cccc68dbe47ec33751a4c6c9092441a4c6b9404e016763a45fbba1232cf98f3dfba53104307cb2e6d0e28770adb10ee5c7c241250b5ba315d0aa8a579",
            }
        }
    },
    {
        "Beginning Orchestra - Good King Wenceslas Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "64ee158bffc1ad111166a486",
                "sharingKey": "92c21e00de972b59b9a8a58f1d255f01c1f561cfdfca8f4b3de3db9d818632b6cd4ac419eff95e3b41fb7ce0be646d417b34b14f797a4ec23944a6a9af5f7d30",
            }
        }
    },
    {
        "Beginning Orchestra - Good King Wenceslas Bassline": {
            "Concert Pitch BC": {
                "scoreId": "64ee157ad126671ae411ec62",
                "sharingKey": "21c136dde65c2830739dfa4acbcb7f51f09d6f7f6caa27a9c105688fd737be0468ec1274ceb16da7572d4b531a49da74805864b859584959a709b6ece1862e7a",
            }
        }
    },
    {
        "Beginning Orchestra - Hot Cross Buns Melody": {
            "Alto Clef": {
                "scoreId": "64ee14cc1ca3db74f91f96ee",
                "sharingKey": "a33256abaff364a60e5c53561dbde5b262b2a3ef6e1ad8fbbc4921a7489a8c0b927e79e9cf4532ca8aeb75db3b58bb7d873962992f6e533f3046d1dcefdeed2c",
            }
        }
    },
    {
        "Beginning Orchestra - Hot Cross Buns Melody": {
            "Concert Pitch TC": {
                "scoreId": "64ee14b4edff21852528c247",
                "sharingKey": "482266f7e03a7db7c4702deb2bb0f14357e17da7a7518d850dfdbbcaa5e14a3fb5d50c373172adfb7646929bf3dee1aa872023a4f4807bfb458ce6909379ceaa",
            }
        }
    },
    {
        "Beginning Orchestra - Hot Cross Buns Melody": {
            "Concert Pitch BC 8vb": {
                "scoreId": "64ee14f2f3d6d8c5edbb0900",
                "sharingKey": "129907e0dc8fe4b49981a12ffe24c8c679844336ed73f56a427e40080451df79834038eb9542828d3cf2d5771cc9db0b34aa8d69a877d5dc5d659fbb42c62e6e",
            }
        }
    },
    {
        "Beginning Orchestra - Hot Cross Buns Melody": {
            "Concert Pitch BC": {
                "scoreId": "64ee14de069618a0c0aac2d1",
                "sharingKey": "75b3fc1733347427b5286c1280364f592631e6cc580b7539dd48bfca0f9d04c2578f70c20931e7101537c881b09db20ba8cd25baaf8543bcf057c0aa9f6be829",
            }
        }
    },
    {
        "Beginning Orchestra - Hot Cross Buns Bassline": {
            "Alto Clef": {
                "scoreId": "64ee14cc61b1b596704490f6",
                "sharingKey": "6a92094daf19cb83bb68bb27f6b9427f604fda9d9436aac0ffc5775af3c00faace9c7a2b0dddd43e2e1432a1915b19f734b07e9677fd4b5a24681a7961103681",
            }
        }
    },
    {
        "Beginning Orchestra - Hot Cross Buns Bassline": {
            "Concert Pitch TC": {
                "scoreId": "64ee14b4f43f9ddb80b9e0c8",
                "sharingKey": "d2092024a7367ff14dbbc2e913c49de1373863439d3dc326dfb1f84bc3b494e276eab0ea9973873cd8da783892ac653b92f5d70c97b8b4db3722ad2e83126727",
            }
        }
    },
    {
        "Beginning Orchestra - Hot Cross Buns Bassline": {
            "Concert Pitch BC 8vb": {
                "scoreId": "64ee14f21f65ea105c229704",
                "sharingKey": "02d39c2997095159fbbb4f8b1bdbeb99a872cc0ec9623207f8a48685b113e5e4f2d1ac83ec3b28f2a921018fda85443521901c3bffd205df6abbe8141d8da760",
            }
        }
    },
    {
        "Beginning Orchestra - Hot Cross Buns Bassline": {
            "Concert Pitch BC": {
                "scoreId": "64ee14de20ad411b169a72bf",
                "sharingKey": "c2efe7b39227d4987da25eedae3cbe890d704b128f00fb14b9659bdbd34513ae90be9604269dc160d90af9e932d667c721a0109cd743dc0fee6bc3dafa10fdd2",
            }
        }
    },
]

for piece in from_xml:
    for piece_part, part_trans in piece.items():
        if piece_part not in flatios:
            flatios[piece_part] = {}
        for transp, flat_info in part_trans.items():
            flatios[piece_part][transp] = flat_info


def update_site_forward(apps, schema_editor):
    # I manually created a piece in dev, so I need to not check because i didn't make all the parts I was supposed to
    for piece in data:
        for part in piece["parts"]:
            for t in part["transpositions"]:
                t["flatio"] = json.dumps(flatios[part["name"]][t["transposition"]])
        serializer = PieceCreateSerializer(data=piece)
        serializer.is_valid()
        serializer.create(serializer.validated_data)


class Migration(migrations.Migration):
    dependencies = [
        ("musics", "0019_auto_20230911_seed_beginning_band"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
