# Generated by Django 3.2.11 on 2023-09-20 14:15

from django.db import migrations

from teleband.musics.api.serializers import *

parts = {
    "Air for Band Melody": "sample_audio/Air for Band Trumpet_Melody.mp3",
    "Air for Band Bassline": "sample_audio/Air for Band Bass Line.mp3",
    "Celebration for a New Day Melody": "sample_audio/Celebration of a New Day Melody Recording.mp3",
    "Celebration for a New Day Bassline": "sample_audio/Celebration of New Day Bass Line Recording.mp3",
    "America the Beautiful Melody": "sample_audio/America the Beautiful Melody Recording.mp3",
    "America the Beautiful Bassline": "sample_audio/America the Beautiful Bass Line Recording.mp3",
    "The Favorite Melody": "sample_audio/The Favorite Melody Recording.mp3",
    "The Favorite Bassline": "sample_audio/The Favorite Bass Line.mp3",
    "Freedom 2040 (Band) Melody": "sample_audio/Freedom 2040 - Melody.mp3",
    "Freedom 2040 (Band) Bassline": "sample_audio/Freedom 2040 - Bassline.mp3",
    "Freedom 2040 (Orchestra) Melody": "sample_audio/Freedom 2040 -Orchestra- - Melody -F-.mp3",
    "Freedom 2040 (Orchestra) Bassline": "sample_audio/Freedom 2040 -Orchestra- - Bass Line  -F-.mp3",
    "Down by the Riverside Melody": "sample_audio/Down by the Riverside - Melody.mp3",
    "Down by the Riverside Bassline": "sample_audio/Down by the Riverside - Bassline.mp3",
    "Deep River Melody": "sample_audio/Deep River - Melody.mp3",
    "Deep River Bassline": "sample_audio/Deep River - Bassline.mp3",
    "I Want to be Ready Melody": "sample_audio/I Want to be Ready - Melody.mp3",
    "I Want to be Ready Bassline": "sample_audio/I Want to be Ready - Bassline.mp3",
    "Beginning Band - When the Saints Go Marching In Melody": "sample_audio/When the Saints Bass-beg-band-sample.mp3",
    "Beginning Band - When the Saints Go Marching In Bassline": "sample_audio/When the Saints - Melody-beg-band-sample.mp3",
    "Beginning Band - Ode to Joy Melody": "sample_audio/ODE TO JOY Melody Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - Ode to Joy Bassline": "sample_audio/ODE TO JOY Bass Line Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - London Bridge Melody": "sample_audio/LONDON BRIDGE Melody Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - London Bridge Bassline": "sample_audio/LONDON BRIDGE Bass Line Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - Jolly Old St. Nick Melody": "sample_audio/JOLLY OLD ST. NICHOLAS Melody Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - Jolly Old St. Nick Bassline": "sample_audio/JOLLY OLD ST. NICHOLAS Bass Line Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - Jingle Bells Melody": "sample_audio/JINGLE BELLS Melody Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - Jingle Bells Bassline": "sample_audio/JINGLE BELLS Bass Line Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - Hot Cross Buns Melody": "sample_audio/HOT CROSS BUNS Melody Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - Hot Cross Buns Bassline": "sample_audio/HOT CROSS BUNS Bass Line Concert Pitch-beg-band-sample.mp3",
    "Beginning Band - Good King Wenceslas Melody": "sample_audio/Good King Wenceslas - Melody-beg-band-sample.mp3",
    "Beginning Band - Good King Wenceslas Bassline": "sample_audio/Good King Wenceslas - Bass-beg-band-sample.mp3",
    "Beginning Band - Go Tell Aunt Rhody Melody": "sample_audio/Go Tell Aunt Rhody Melody -beg-band-sample.mp3",
    "Beginning Band - Go Tell Aunt Rhody Bassline": "sample_audio/Go Tell Aunt Rhody - Bass-beg-band-sample.mp3",
    "Beginning Band - Aura Lee Melody": "sample_audio/Aura Lee - Melody-beg-band-sample.mp3",
    "Beginning Band - Aura Lee Bassline": "sample_audio/Aura Lee - Bass-beg-band-sample.mp3",
    "Beginning Band - Amazing Grace Melody": "sample_audio/Amazing Grace - Melody-beg-band-sample.mp3",
    "Beginning Band - Amazing Grace Bassline": "sample_audio/Amazing_Grace_-_Bass-beg-band-sample.mp3",
    "Beginning Orchestra - Bile em Cabbage Down Melody": "sample_audio/Bile em Cabbage Down - Melody-beg-orch-sample.mp3",
    "Beginning Orchestra - Bile em Cabbage Down Bassline": "sample_audio/Bile em Cabbage Down - Bassline-beg-orch-sample.mp3",
    "Beginning Orchestra - Go Tell Aunt Rhody Melody": "sample_audio/Go Tell Aunt Rhody - Melody-beg-orch-sample.mp3",
    "Beginning Orchestra - Go Tell Aunt Rhody Bassline": "sample_audio/Go Tell Aunt Rhody -Bassline-beg-orch-sample.mp3",
    "Beginning Orchestra - Good King Wenceslas Melody": "sample_audio/Good King Wenceslas - Melody-beg-orch-sample.mp3",
    "Beginning Orchestra - Good King Wenceslas Bassline": "sample_audio/Good King Wenceslas - Bassline-beg-orch-sample.mp3",
    "Beginning Orchestra - Hot Cross Buns Melody": "sample_audio/Hot Cross Buns - Melody-beg-orch-sample.mp3",
    "Beginning Orchestra - Hot Cross Buns Bassline": "sample_audio/Hot Cross Buns - Bassline-beg-orch-sample.mp3",
}


def update_site_forward(apps, schema_editor):
    Part = apps.get_model("musics", "Part")
    for part_name, part_sample in parts.items():
        part = Part.objects.get(name=part_name)
        part.sample_audio = part_sample
        part.save()


class Migration(migrations.Migration):
    dependencies = [
        ("musics", "0020_auto_20230918_1451_seed_beginning_orchestra"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
