# Generated by Django 3.2.11 on 2024-02-23 15:15

from django.db import migrations

T = "tonic"
S = "subdominant"
D = "dominant"
A = "applied"

data = {
    "Down by the Riverside Melody": [T, T, T, D, T, T, T, D, T, S, T, D, T, S, T, D, T],
    "Deep River Melody": [T, T, S, D, T, S, D, D, T, T, S, S, T, S, D, T],
}


def update_site_forward(apps, schema_editor):
    Part = apps.get_model("musics", "Part")
    pattenered_parts = Part.objects.filter(name__in=list(data))
    for p in pattenered_parts:
        p.chord_scale_pattern = data[p.name]
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0024_auto_20231030_2217_piece_slugs'),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
