# Generated by Django 3.2.11 on 2024-03-15 18:20

from django.db import migrations


def update_site_forward(apps, schema_editor):
    Piece = apps.get_model("musics", "Piece")
    Part = apps.get_model("musics", "Part")
    PartTransposition = apps.get_model("musics", "PartTransposition")
    PartType = apps.get_model("musics", "PartType")
    Transposition = apps.get_model("instruments", "Transposition")
    
    deep_river, deep_river_created = Piece.objects.get_or_create(name="Deep River") 
    melody, melody_created = PartType.objects.get_or_create(name="Melody")
    bassline, bassline_created = PartType.objects.get_or_create(name="Bassline")

    dr_melody, dr_melody_created = Part.objects.get_or_create(piece=deep_river, part_type=melody)
    dr_bassline, dr_bassline_created = Part.objects.get_or_create(piece=deep_river, part_type=bassline)

    concert_tc, concert_tc_created = Transposition.objects.get_or_create(name="Concert Pitch TC")
    concert_bc, concert_bc_created = Transposition.objects.get_or_create(name="Concert Pitch BC")

    dr_melody_tc, dr_melody_tc_created = PartTransposition.objects.get_or_create(part=dr_melody, transposition=concert_tc)
    dr_melody_tc.flatio = '{"scoreId": "65f3164ea114758e30975d47", "sharingKey": "89b9d230dddd45edd858af771f3630b148705b2f5fa361678cf46864697cee3611f4dd49494c307513e8d261f65221692de79b474882560b649249fe2f2ad7b2"}'
    dr_melody_tc.save()

    dr_bassline_bc, dr_bassline_bc_created = PartTransposition.objects.get_or_create(part=dr_bassline, transposition=concert_bc)
    dr_bassline_bc.flatio = '{"scoreId": "65f317750f4bde10c7aff326", "sharingKey": "6a9ecd6102c4d6be5b104679a0d74def797b7022ffa45c8cdb75aa1f2aec952eb94684b32333a67056eb7a115f69b4ba13023b6faa1ecda35a0154e131b85210"}'
    dr_bassline_bc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0025_auto_20240223_1015'),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
