# Generated by Django 3.2.11 on 2022-01-11 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0003_data_migration_seed_instruments"),
        ("courses", "0002_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2022, 1, 11, 1, 52, 38, 716619, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2022, 1, 11, 1, 52, 44, 131728, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="instrument",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.instrument",
            ),
        ),
    ]
