# Generated by Django 3.2.11 on 2024-04-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_data_migration_demo_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='can_edit_instruments',
            field=models.BooleanField(default=False),
        ),
    ]
