# Generated by Django 3.2.11 on 2022-01-08 02:33

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    ActivityCategory = apps.get_model("assignments", "ActivityCategory")
    for category in ["Perform", "Create", "Respond", "Connect"]:
        ActivityCategory.objects.update_or_create(
            name=category,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_site_forward, migrations.RunPython.noop)
    ]
