# Generated by Django 3.2.11 on 2022-01-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("assignments", "0003_seed_activity_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.course",
            ),
        ),
    ]
