# Generated by Django 3.2.11 on 2022-01-08 20:17

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Assignment = apps.get_model("assignments", "Assignment")
    Assignment.objects.filter(course=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_course'),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
