# Generated by Django 3.2.11 on 2022-01-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_enrollment_unique_together"),
        ("assignments", "0007_assignment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="enrollment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.enrollment",
            ),
        ),
    ]
