# Generated by Django 3.2.11 on 2022-01-13 18:56

from django.db import migrations


def update_site_forward(apps, schema_editor):
    Assignment = apps.get_model("assignments", "Assignment")
    Enrollment = apps.get_model("courses", "Enrollment")

    for a in Assignment.objects.all():
        try:
            e = Enrollment.objects.get(user=a.user, course=a.course)
            a.enrollment = e
            a.save()
        except Enrollment.DoesNotExist:
            print(
                "ERROR: deleting Assignment with nonexistent Enrollment for course {} user {}".format(
                    a.course, a.user
                )
            )
            a.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0008_assignment_enrollment"),
        ("courses", "0004_alter_enrollment_unique_together"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
