# Generated by Django 3.2.11 on 2022-01-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0009_populate_enrollments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="user",
        ),
    ]
