# Generated by Django 3.2.11 on 2022-01-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0004_auto_20220113_2122"),
        ("assignments", "0011_alter_assignment_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="part",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="musics.part"
            ),
        ),
    ]
