# Generated by Django 3.2.11 on 2022-01-14 02:26

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Assignment = apps.get_model("assignments", "Assignment")

    for a in Assignment.objects.all():
        a.part = a.activity.part.part
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0012_assignment_part"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
