# Generated by Django 3.2.11 on 2022-01-14 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0007_alter_part_part_type"),
        ("assignments", "0013_legitimize_assignment_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="part",
        ),
        migrations.AddField(
            model_name="activity",
            name="part_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="musics.parttype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="musics.part"
            ),
        ),
    ]
