# Generated by Django 3.2.11 on 2022-01-15 02:26

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Activity = apps.get_model("assignments", "Activity")
    ActivityType = apps.get_model("assignments", "ActivityType")
    PartType = apps.get_model("musics", "PartType")

    Activity.objects.update_or_create(
        activity_type=ActivityType.objects.get(name="Melody"),
        part_type=PartType.objects.get(name="Melody"),
        body="Practice the melody and then record yourself performing it.",
    )
    Activity.objects.update_or_create(
        activity_type=ActivityType.objects.get(name="Bassline"),
        part_type=PartType.objects.get(name="Bassline"),
        body="Practice the bassline and then record yourself performing it.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0014_auto_20220113_2131"),
        ("musics", "0011_seed_piece_parts_parttranspositions"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
