# Generated by Django 3.2.11 on 2022-02-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0015_auto_20220206_2027'),
        ('assignments', '0015_seed_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='part_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='musics.parttype'),
        ),
    ]
