# Generated by Django 3.2.11 on 2022-02-22 03:55

from django.db import migrations

def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Activity = apps.get_model("assignments", "Activity")
    ActivityType = apps.get_model("assignments", "ActivityType")

    Activity.objects.update_or_create(
        activity_type=ActivityType.objects.get(name="Creativity"),
        body="INSTRUCTIONS: 1) Now that you know the melody and bass line think like a composer and create a counter-melody that would sound good when played with the melody and bass line. 2) To practice creating a counter-melody, first review the main melody and bass line by performing them with the accompaniment track. 3) Experiment with changing just a few notes from the melody. Continue until you are comfortable with your counter-melody. Optional: practice playing with the recording of the melody so you can hear how your counter-melody sounds with the original melody. Record your counter-melody with the accompaniment track and submit for review. Notate your counter-melody.",
    )
    Activity.objects.update_or_create(
        activity_type=ActivityType.objects.get(name="Reflection"),
        body="INSTRUCTIONS: 1) Reflect on your performance of what you uploaded in Assignment 1 (Melody). 2) Review the attached rating scales and score yourself. 3) Mark your score in the appropriate space. 4) Write 2-3 sentences about your performance.",
    )

    at = ActivityType.objects.get(name="Melody")
    at.body = "INSTRUCTIONS: 1) Familiarize yourself with the notation. 2) Listen to the sample performance. 3) Practice performing with the accompaniment track. 4) Record your performance with the accompaniment track. You may record several times until you are satisfied with your performance. 5) Submit your recording."
    at.save()

    at = ActivityType.objects.get(name="Bassline")
    at.body = "INSTRUCTIONS: 1) Familiarize yourself with the notation. 2) Listen to the sample performance. 3) Practice performing with the accompaniment track. 4) Record your performance with the accompaniment track. You may record several times until you are satisfied with your performance. 5) Submit your recording."
    at.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_alter_activity_part_type'),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
