# Generated by Django 3.2.11 on 2022-06-18 02:11

from django.db import migrations


def assign_part_type(apps, schema_editor):
    """Set site domain and name."""
    Activity = apps.get_model("assignments", "Activity")
    ActivityType = apps.get_model("assignments", "ActivityType")
    PartType = apps.get_model("musics", "PartType")
    combined_part_type = PartType.objects.get(name="Combined")
    record = Activity.objects.get(activity_type=ActivityType.objects.get(name="Creativity"),)
    record.part_type=combined_part_type
    record.save()
    record = Activity.objects.get(activity_type=ActivityType.objects.get(name="Reflection"),)
    record.part_type=combined_part_type
    record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_seed_more_activities'),
    ]

    operations = [migrations.RunPython(assign_part_type, migrations.RunPython.noop)]
