# Generated by Django 3.2.11 on 2023-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_auto_20230408_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurriculumPiecePlan',
            new_name='CurriculumEntry',
        ),
        migrations.RenameModel(
            old_name='PiecePlanActivity',
            new_name='PlannedActivity',
        ),
        migrations.RemoveField(
            model_name='pieceplan',
            name='ordered',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='number_of_submissions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
