# Generated by Django 3.2.11 on 2023-05-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_auto_20230517_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='number_of_submissions',
        ),
        migrations.AddField(
            model_name='activity',
            name='number_of_submissions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
