# Generated by Django 3.2.11 on 2023-06-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0022_move_number_of_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='piece_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assignments.pieceplan'),
        ),
        migrations.AddField(
            model_name='pieceplan',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
