# Generated by Django 3.2.11 on 2023-06-03 17:26

from django.db import migrations

def update_site_forward(apps, schema_editor):
    """ 1. Iterate through all Assignments.
        2. Create a list containing all unique combinations of Assignment.activity and Assignment.part.piece.
        3. For each unique combination, create a new PiecePlan named for the Piece and Activity.
        3. For each new PiecePlan, create a new PlannedActivity, with the same Activity as the Assignment.
        4. Associate the new PlannedActivity with the new PiecePlan.
        5. Associate the new PiecePlan with every assignment with the same activity and piece."""
    
    Assignment = apps.get_model("assignments", "Assignment")
    PlannedActivity = apps.get_model("assignments", "PlannedActivity")
    PiecePlan = apps.get_model("assignments", "PiecePlan")

    assignments = Assignment.objects.all()
    unique_assignments = set([(assignment.activity, assignment.part.piece) for assignment in assignments])

    for activity, piece in unique_assignments:
        piece_plan = PiecePlan.objects.create(name=f"{piece.name} - {activity.activity_type.name}", piece=piece, ordered=False)
        planned_activity = PlannedActivity.objects.create(activity=activity, piece_plan=piece_plan, order=0)
        piece_plan.save()

        for assignment in assignments.filter(activity=activity, part__piece=piece):
            assignment.piece_plan = piece_plan
            assignment.save()

def update_site_backward(apps, schema_editor):
    """ 1. Remove all references to PiecePlan from Assignments.
        2. Delete all PlannedActivities.
        3. Delete all PiecePlans. """
    
    Assignment = apps.get_model("assignments", "Assignment")
    PlannedActivity = apps.get_model("assignments", "PlannedActivity")
    PiecePlan = apps.get_model("assignments", "PiecePlan")

    assignments = Assignment.objects.all()
    planned_activities = PlannedActivity.objects.all()
    piece_plans = PiecePlan.objects.all()

    for assignment in assignments:
        assignment.piece_plan = None
        assignment.save()

    planned_activities.delete()
    piece_plans.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0023_auto_20230602_1258'),
    ]

    operations = [
        migrations.RunPython(update_site_forward, update_site_backward)
    ]
