# Generated by Django 3.2.11 on 2023-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0023_assignment_piece_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
