# Generated by Django 3.2.11 on 2023-06-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0024_create_pieceplans_for_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumentry',
            options={'ordering': ['order'], 'verbose_name': 'Curriculum Entry', 'verbose_name_plural': 'Curriculum Entries'},
        ),
        migrations.AlterModelOptions(
            name='pieceplan',
            options={'verbose_name': 'Piece Plan'},
        ),
        migrations.AlterModelOptions(
            name='plannedactivity',
            options={'ordering': ['order'], 'verbose_name': 'Planned Activity', 'verbose_name_plural': 'Planned Activities'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='activity',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='piece_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='assignments.pieceplan'),
        ),
    ]
