# Generated by Django 3.2.11 on 2023-06-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0018_seed_more_music'),
        ('assignments', '0025_migrate_activity_type_and_category_20230613_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musics.piece'),
        ),
    ]
