# Generated by Django 3.2.11 on 2023-06-13 17:19

from django.db import migrations

def move_piece_to_assignment(apps, schema_editor):
    Assignment = apps.get_model("assignments", "Assignment")
    Part = apps.get_model("musics", "Part")
    for assignment in Assignment.objects.all():
        assignment.piece = assignment.part.piece
        assignment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0026_assignment_piece'),
    ]

    operations = [
        migrations.RunPython(move_piece_to_assignment)
    ]
