# Generated by Django 3.2.11 on 2024-03-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0033_auto_20240312_2321'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('activity', 'enrollment', 'piece'), name='unique_assignment'),
        ),
    ]
