# Generated by Django 3.2.11 on 2022-01-07 02:48

from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Role = apps.get_model("users", "Role")
    Role.objects.update_or_create(
        name="Teacher",
    )
    Role.objects.update_or_create(
        name="Student",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220106_2115"),
    ]

    operations = [migrations.RunPython(update_site_forward, migrations.RunPython.noop)]
