# Generated by Django 3.2.11 on 2022-01-17 01:57

from django.db import migrations


def migrate_site_forward(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.update_or_create(name="Teacher")
    Group.objects.update_or_create(name="Student")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_data_migration_demo_users"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [migrations.RunPython(migrate_site_forward, migrations.RunPython.noop)]
