# Generated by Django 3.2.11 on 2022-01-17 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0004_alter_invitation_id"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_seed_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupInvitation",
            fields=[
                (
                    "invitation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="invitations.invitation",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="auth.group"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("invitations.invitation",),
        ),
    ]
