# Generated by Django 3.2.11 on 2022-01-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0003_data_migration_seed_instruments"),
        ("users", "0006_groupinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="instrument",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="instruments.instrument",
            ),
        ),
    ]
