# Generated by Django 3.2.11 on 2022-01-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_instrument"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
