# Generated by Django 3.2.11 on 2022-01-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_data_migration_teacher_django_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, help_text="Any string that is meaningful to the user's educational institution.", max_length=255, verbose_name='External ID'),
        ),
    ]
